// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { LoanEntity } from "./loan_entity";
import { LoanObservation } from "./loan_observation";
import { ObserveVote } from "./observe_vote";
import { Params } from "./params";
import { LoanTransaction } from "./transaction";

export const protobufPackage = "cfprotocol.loan";

/** GenesisState defines the loan module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  loanTransactionList: LoanTransaction[];
  loanTransactionCount: number;
  loanObservationList: LoanObservation[];
  loanObservationCount: number;
  observeVoteList: ObserveVote[];
  observeVoteCount: number;
  loanEntityList: LoanEntity[];
  loanEntityCount: number;
}

function createBaseGenesisState(): GenesisState {
  return {
    params: undefined,
    loanTransactionList: [],
    loanTransactionCount: 0,
    loanObservationList: [],
    loanObservationCount: 0,
    observeVoteList: [],
    observeVoteCount: 0,
    loanEntityList: [],
    loanEntityCount: 0,
  };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.loanTransactionList) {
      LoanTransaction.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.loanTransactionCount !== 0) {
      writer.uint32(24).uint64(message.loanTransactionCount);
    }
    for (const v of message.loanObservationList) {
      LoanObservation.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.loanObservationCount !== 0) {
      writer.uint32(40).uint64(message.loanObservationCount);
    }
    for (const v of message.observeVoteList) {
      ObserveVote.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.observeVoteCount !== 0) {
      writer.uint32(56).uint64(message.observeVoteCount);
    }
    for (const v of message.loanEntityList) {
      LoanEntity.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.loanEntityCount !== 0) {
      writer.uint32(72).uint64(message.loanEntityCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.loanTransactionList.push(LoanTransaction.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.loanTransactionCount = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.loanObservationList.push(LoanObservation.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.loanObservationCount = longToNumber(reader.uint64());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.observeVoteList.push(ObserveVote.decode(reader, reader.uint32()));
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.observeVoteCount = longToNumber(reader.uint64());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.loanEntityList.push(LoanEntity.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.loanEntityCount = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      loanTransactionList: globalThis.Array.isArray(object?.loanTransactionList)
        ? object.loanTransactionList.map((e: any) => LoanTransaction.fromJSON(e))
        : [],
      loanTransactionCount: isSet(object.loanTransactionCount) ? globalThis.Number(object.loanTransactionCount) : 0,
      loanObservationList: globalThis.Array.isArray(object?.loanObservationList)
        ? object.loanObservationList.map((e: any) => LoanObservation.fromJSON(e))
        : [],
      loanObservationCount: isSet(object.loanObservationCount) ? globalThis.Number(object.loanObservationCount) : 0,
      observeVoteList: globalThis.Array.isArray(object?.observeVoteList)
        ? object.observeVoteList.map((e: any) => ObserveVote.fromJSON(e))
        : [],
      observeVoteCount: isSet(object.observeVoteCount) ? globalThis.Number(object.observeVoteCount) : 0,
      loanEntityList: globalThis.Array.isArray(object?.loanEntityList)
        ? object.loanEntityList.map((e: any) => LoanEntity.fromJSON(e))
        : [],
      loanEntityCount: isSet(object.loanEntityCount) ? globalThis.Number(object.loanEntityCount) : 0,
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.loanTransactionList?.length) {
      obj.loanTransactionList = message.loanTransactionList.map((e) => LoanTransaction.toJSON(e));
    }
    if (message.loanTransactionCount !== 0) {
      obj.loanTransactionCount = Math.round(message.loanTransactionCount);
    }
    if (message.loanObservationList?.length) {
      obj.loanObservationList = message.loanObservationList.map((e) => LoanObservation.toJSON(e));
    }
    if (message.loanObservationCount !== 0) {
      obj.loanObservationCount = Math.round(message.loanObservationCount);
    }
    if (message.observeVoteList?.length) {
      obj.observeVoteList = message.observeVoteList.map((e) => ObserveVote.toJSON(e));
    }
    if (message.observeVoteCount !== 0) {
      obj.observeVoteCount = Math.round(message.observeVoteCount);
    }
    if (message.loanEntityList?.length) {
      obj.loanEntityList = message.loanEntityList.map((e) => LoanEntity.toJSON(e));
    }
    if (message.loanEntityCount !== 0) {
      obj.loanEntityCount = Math.round(message.loanEntityCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.loanTransactionList = object.loanTransactionList?.map((e) => LoanTransaction.fromPartial(e)) || [];
    message.loanTransactionCount = object.loanTransactionCount ?? 0;
    message.loanObservationList = object.loanObservationList?.map((e) => LoanObservation.fromPartial(e)) || [];
    message.loanObservationCount = object.loanObservationCount ?? 0;
    message.observeVoteList = object.observeVoteList?.map((e) => ObserveVote.fromPartial(e)) || [];
    message.observeVoteCount = object.observeVoteCount ?? 0;
    message.loanEntityList = object.loanEntityList?.map((e) => LoanEntity.fromPartial(e)) || [];
    message.loanEntityCount = object.loanEntityCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
