// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/lock/observe_vote_locking.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.lock";

/** ObserveVoteLocking defines the payload of asset locking vote. */
export interface ObserveVoteLocking {
  id: number;
  voter: string;
  lockTxId: number;
  btcTxHash: string;
  status: boolean;
  failReason: string;
  used: boolean;
  amount: string;
}

function createBaseObserveVoteLocking(): ObserveVoteLocking {
  return { id: 0, voter: "", lockTxId: 0, btcTxHash: "", status: false, failReason: "", used: false, amount: "" };
}

export const ObserveVoteLocking: MessageFns<ObserveVoteLocking> = {
  encode(message: ObserveVoteLocking, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.voter !== "") {
      writer.uint32(18).string(message.voter);
    }
    if (message.lockTxId !== 0) {
      writer.uint32(24).uint64(message.lockTxId);
    }
    if (message.btcTxHash !== "") {
      writer.uint32(34).string(message.btcTxHash);
    }
    if (message.status !== false) {
      writer.uint32(40).bool(message.status);
    }
    if (message.failReason !== "") {
      writer.uint32(50).string(message.failReason);
    }
    if (message.used !== false) {
      writer.uint32(56).bool(message.used);
    }
    if (message.amount !== "") {
      writer.uint32(66).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObserveVoteLocking {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObserveVoteLocking();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.voter = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.lockTxId = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.btcTxHash = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.status = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.failReason = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.used = reader.bool();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.amount = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObserveVoteLocking {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      voter: isSet(object.voter) ? globalThis.String(object.voter) : "",
      lockTxId: isSet(object.lockTxId) ? globalThis.Number(object.lockTxId) : 0,
      btcTxHash: isSet(object.btcTxHash) ? globalThis.String(object.btcTxHash) : "",
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      failReason: isSet(object.failReason) ? globalThis.String(object.failReason) : "",
      used: isSet(object.used) ? globalThis.Boolean(object.used) : false,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
    };
  },

  toJSON(message: ObserveVoteLocking): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.voter !== "") {
      obj.voter = message.voter;
    }
    if (message.lockTxId !== 0) {
      obj.lockTxId = Math.round(message.lockTxId);
    }
    if (message.btcTxHash !== "") {
      obj.btcTxHash = message.btcTxHash;
    }
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.failReason !== "") {
      obj.failReason = message.failReason;
    }
    if (message.used !== false) {
      obj.used = message.used;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObserveVoteLocking>, I>>(base?: I): ObserveVoteLocking {
    return ObserveVoteLocking.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObserveVoteLocking>, I>>(object: I): ObserveVoteLocking {
    const message = createBaseObserveVoteLocking();
    message.id = object.id ?? 0;
    message.voter = object.voter ?? "";
    message.lockTxId = object.lockTxId ?? 0;
    message.btcTxHash = object.btcTxHash ?? "";
    message.status = object.status ?? false;
    message.failReason = object.failReason ?? "";
    message.used = object.used ?? false;
    message.amount = object.amount ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
