// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/asset/profile.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AssetType, assetTypeFromJSON, assetTypeToJSON } from "./type";

export const protobufPackage = "cfprotocol.asset";

/** AssetProfile defines the asset base information. */
export interface AssetProfile {
  /** asset id */
  id: number;
  /** asset symbol i.e. BTC */
  symbol: string;
  /** asset name i.e. Bitcoin, Rune */
  name: string;
  /** total supply */
  totalSupply: string;
  /** decimal number */
  decimals: number;
  /** specific item for ERC20 only */
  contractAddress: string;
  /** specific item for ERC20 and BRC20 */
  deployerAddress: string;
  /** specific item for BRC20 only */
  inscriptionId: string;
  /** specific item for Runes only */
  runeId: string;
  /** asset type */
  assetType: AssetType;
}

function createBaseAssetProfile(): AssetProfile {
  return {
    id: 0,
    symbol: "",
    name: "",
    totalSupply: "",
    decimals: 0,
    contractAddress: "",
    deployerAddress: "",
    inscriptionId: "",
    runeId: "",
    assetType: 0,
  };
}

export const AssetProfile: MessageFns<AssetProfile> = {
  encode(message: AssetProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.totalSupply !== "") {
      writer.uint32(34).string(message.totalSupply);
    }
    if (message.decimals !== 0) {
      writer.uint32(40).uint64(message.decimals);
    }
    if (message.contractAddress !== "") {
      writer.uint32(50).string(message.contractAddress);
    }
    if (message.deployerAddress !== "") {
      writer.uint32(58).string(message.deployerAddress);
    }
    if (message.inscriptionId !== "") {
      writer.uint32(66).string(message.inscriptionId);
    }
    if (message.runeId !== "") {
      writer.uint32(74).string(message.runeId);
    }
    if (message.assetType !== 0) {
      writer.uint32(80).int32(message.assetType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.totalSupply = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.decimals = longToNumber(reader.uint64());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.contractAddress = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.deployerAddress = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.inscriptionId = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.runeId = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.assetType = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetProfile {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      totalSupply: isSet(object.totalSupply) ? globalThis.String(object.totalSupply) : "",
      decimals: isSet(object.decimals) ? globalThis.Number(object.decimals) : 0,
      contractAddress: isSet(object.contractAddress) ? globalThis.String(object.contractAddress) : "",
      deployerAddress: isSet(object.deployerAddress) ? globalThis.String(object.deployerAddress) : "",
      inscriptionId: isSet(object.inscriptionId) ? globalThis.String(object.inscriptionId) : "",
      runeId: isSet(object.runeId) ? globalThis.String(object.runeId) : "",
      assetType: isSet(object.assetType) ? assetTypeFromJSON(object.assetType) : 0,
    };
  },

  toJSON(message: AssetProfile): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.totalSupply !== "") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.decimals !== 0) {
      obj.decimals = Math.round(message.decimals);
    }
    if (message.contractAddress !== "") {
      obj.contractAddress = message.contractAddress;
    }
    if (message.deployerAddress !== "") {
      obj.deployerAddress = message.deployerAddress;
    }
    if (message.inscriptionId !== "") {
      obj.inscriptionId = message.inscriptionId;
    }
    if (message.runeId !== "") {
      obj.runeId = message.runeId;
    }
    if (message.assetType !== 0) {
      obj.assetType = assetTypeToJSON(message.assetType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetProfile>, I>>(base?: I): AssetProfile {
    return AssetProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetProfile>, I>>(object: I): AssetProfile {
    const message = createBaseAssetProfile();
    message.id = object.id ?? 0;
    message.symbol = object.symbol ?? "";
    message.name = object.name ?? "";
    message.totalSupply = object.totalSupply ?? "";
    message.decimals = object.decimals ?? 0;
    message.contractAddress = object.contractAddress ?? "";
    message.deployerAddress = object.deployerAddress ?? "";
    message.inscriptionId = object.inscriptionId ?? "";
    message.runeId = object.runeId ?? "";
    message.assetType = object.assetType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
