// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/tss/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../cosmos/base/query/v1beta1/pagination";
import { Params } from "./params";
import { Pubkey } from "./pubkey";
import { TssPubkey } from "./tss_pubkey";
import { KeygenBlock } from "./type_keygen";

export const protobufPackage = "cfprotocol.tss";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryPubkeyRequest is request type for the Query/PubkeyRequest RPC method. */
export interface QueryPubkeyRequest {
  id: number;
}

/** QueryPubkeyResponse is response type for the Query/PubkeyRequest RPC method. */
export interface QueryPubkeyResponse {
  pubkey: Pubkey | undefined;
}

/** QueryAllPubkeyRequest is response type for the Query/AllPubkeyRequest RPC method. */
export interface QueryAllPubkeyRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllPubkeyResponse is response type for the Query/AllPubkeyResponse RPC method. */
export interface QueryPubkeyAllResponse {
  pubkey: Pubkey[];
  pagination: PageResponse | undefined;
}

/** QueryKeygenBlockRequest is response type for the Query/KeygenBlockRequest RPC method. */
export interface QueryKeygenBlockRequest {
}

/** QueryListAllNewPubkeyRequest is response type for the Query/AllNewPubkeyRequest RPC method. */
export interface QueryListAllNewPubkeyRequest {
}

/** QueryListAllNewPubkeyResponse is response type for the Query/AllNewPubkeyRequest RPC method. */
export interface QueryListAllNewPubkeyResponse {
  pubkey: Pubkey[];
}

/** QueryTssPubkeyRequest is response type for the Query/TssPubkeyRequest RPC method. */
export interface QueryTssPubkeyRequest {
  id: number;
}

/** QueryTssPubkeyResponse is response type for the Query/TssPubkeyRequest RPC method. */
export interface QueryTssPubkeyResponse {
  tssPubkey: TssPubkey | undefined;
}

/** QueryAllTssPubkeyRequest is response type for the Query/AllTssPubkeyRequest RPC method. */
export interface QueryAllTssPubkeyRequest {
  pagination: PageRequest | undefined;
}

/** QueryTssPubkeyAllResponse is response type for the Query/AllTssPubkeyRequest RPC method. */
export interface QueryTssPubkeyAllResponse {
  tssPubkey: TssPubkey[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryPubkeyRequest(): QueryPubkeyRequest {
  return { id: 0 };
}

export const QueryPubkeyRequest: MessageFns<QueryPubkeyRequest> = {
  encode(message: QueryPubkeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPubkeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPubkeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPubkeyRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryPubkeyRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPubkeyRequest>, I>>(base?: I): QueryPubkeyRequest {
    return QueryPubkeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPubkeyRequest>, I>>(object: I): QueryPubkeyRequest {
    const message = createBaseQueryPubkeyRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryPubkeyResponse(): QueryPubkeyResponse {
  return { pubkey: undefined };
}

export const QueryPubkeyResponse: MessageFns<QueryPubkeyResponse> = {
  encode(message: QueryPubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pubkey !== undefined) {
      Pubkey.encode(message.pubkey, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pubkey = Pubkey.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPubkeyResponse {
    return { pubkey: isSet(object.pubkey) ? Pubkey.fromJSON(object.pubkey) : undefined };
  },

  toJSON(message: QueryPubkeyResponse): unknown {
    const obj: any = {};
    if (message.pubkey !== undefined) {
      obj.pubkey = Pubkey.toJSON(message.pubkey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPubkeyResponse>, I>>(base?: I): QueryPubkeyResponse {
    return QueryPubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPubkeyResponse>, I>>(object: I): QueryPubkeyResponse {
    const message = createBaseQueryPubkeyResponse();
    message.pubkey = (object.pubkey !== undefined && object.pubkey !== null)
      ? Pubkey.fromPartial(object.pubkey)
      : undefined;
    return message;
  },
};

function createBaseQueryAllPubkeyRequest(): QueryAllPubkeyRequest {
  return { pagination: undefined };
}

export const QueryAllPubkeyRequest: MessageFns<QueryAllPubkeyRequest> = {
  encode(message: QueryAllPubkeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllPubkeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllPubkeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllPubkeyRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllPubkeyRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllPubkeyRequest>, I>>(base?: I): QueryAllPubkeyRequest {
    return QueryAllPubkeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllPubkeyRequest>, I>>(object: I): QueryAllPubkeyRequest {
    const message = createBaseQueryAllPubkeyRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPubkeyAllResponse(): QueryPubkeyAllResponse {
  return { pubkey: [], pagination: undefined };
}

export const QueryPubkeyAllResponse: MessageFns<QueryPubkeyAllResponse> = {
  encode(message: QueryPubkeyAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.pubkey) {
      Pubkey.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPubkeyAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPubkeyAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pubkey.push(Pubkey.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPubkeyAllResponse {
    return {
      pubkey: globalThis.Array.isArray(object?.pubkey) ? object.pubkey.map((e: any) => Pubkey.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPubkeyAllResponse): unknown {
    const obj: any = {};
    if (message.pubkey?.length) {
      obj.pubkey = message.pubkey.map((e) => Pubkey.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPubkeyAllResponse>, I>>(base?: I): QueryPubkeyAllResponse {
    return QueryPubkeyAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPubkeyAllResponse>, I>>(object: I): QueryPubkeyAllResponse {
    const message = createBaseQueryPubkeyAllResponse();
    message.pubkey = object.pubkey?.map((e) => Pubkey.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryKeygenBlockRequest(): QueryKeygenBlockRequest {
  return {};
}

export const QueryKeygenBlockRequest: MessageFns<QueryKeygenBlockRequest> = {
  encode(_: QueryKeygenBlockRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryKeygenBlockRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryKeygenBlockRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryKeygenBlockRequest {
    return {};
  },

  toJSON(_: QueryKeygenBlockRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryKeygenBlockRequest>, I>>(base?: I): QueryKeygenBlockRequest {
    return QueryKeygenBlockRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryKeygenBlockRequest>, I>>(_: I): QueryKeygenBlockRequest {
    const message = createBaseQueryKeygenBlockRequest();
    return message;
  },
};

function createBaseQueryListAllNewPubkeyRequest(): QueryListAllNewPubkeyRequest {
  return {};
}

export const QueryListAllNewPubkeyRequest: MessageFns<QueryListAllNewPubkeyRequest> = {
  encode(_: QueryListAllNewPubkeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListAllNewPubkeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListAllNewPubkeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryListAllNewPubkeyRequest {
    return {};
  },

  toJSON(_: QueryListAllNewPubkeyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListAllNewPubkeyRequest>, I>>(base?: I): QueryListAllNewPubkeyRequest {
    return QueryListAllNewPubkeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListAllNewPubkeyRequest>, I>>(_: I): QueryListAllNewPubkeyRequest {
    const message = createBaseQueryListAllNewPubkeyRequest();
    return message;
  },
};

function createBaseQueryListAllNewPubkeyResponse(): QueryListAllNewPubkeyResponse {
  return { pubkey: [] };
}

export const QueryListAllNewPubkeyResponse: MessageFns<QueryListAllNewPubkeyResponse> = {
  encode(message: QueryListAllNewPubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.pubkey) {
      Pubkey.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListAllNewPubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListAllNewPubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pubkey.push(Pubkey.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListAllNewPubkeyResponse {
    return {
      pubkey: globalThis.Array.isArray(object?.pubkey) ? object.pubkey.map((e: any) => Pubkey.fromJSON(e)) : [],
    };
  },

  toJSON(message: QueryListAllNewPubkeyResponse): unknown {
    const obj: any = {};
    if (message.pubkey?.length) {
      obj.pubkey = message.pubkey.map((e) => Pubkey.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListAllNewPubkeyResponse>, I>>(base?: I): QueryListAllNewPubkeyResponse {
    return QueryListAllNewPubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListAllNewPubkeyResponse>, I>>(
    object: I,
  ): QueryListAllNewPubkeyResponse {
    const message = createBaseQueryListAllNewPubkeyResponse();
    message.pubkey = object.pubkey?.map((e) => Pubkey.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryTssPubkeyRequest(): QueryTssPubkeyRequest {
  return { id: 0 };
}

export const QueryTssPubkeyRequest: MessageFns<QueryTssPubkeyRequest> = {
  encode(message: QueryTssPubkeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryTssPubkeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryTssPubkeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryTssPubkeyRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryTssPubkeyRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryTssPubkeyRequest>, I>>(base?: I): QueryTssPubkeyRequest {
    return QueryTssPubkeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryTssPubkeyRequest>, I>>(object: I): QueryTssPubkeyRequest {
    const message = createBaseQueryTssPubkeyRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryTssPubkeyResponse(): QueryTssPubkeyResponse {
  return { tssPubkey: undefined };
}

export const QueryTssPubkeyResponse: MessageFns<QueryTssPubkeyResponse> = {
  encode(message: QueryTssPubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tssPubkey !== undefined) {
      TssPubkey.encode(message.tssPubkey, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryTssPubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryTssPubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.tssPubkey = TssPubkey.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryTssPubkeyResponse {
    return { tssPubkey: isSet(object.tssPubkey) ? TssPubkey.fromJSON(object.tssPubkey) : undefined };
  },

  toJSON(message: QueryTssPubkeyResponse): unknown {
    const obj: any = {};
    if (message.tssPubkey !== undefined) {
      obj.tssPubkey = TssPubkey.toJSON(message.tssPubkey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryTssPubkeyResponse>, I>>(base?: I): QueryTssPubkeyResponse {
    return QueryTssPubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryTssPubkeyResponse>, I>>(object: I): QueryTssPubkeyResponse {
    const message = createBaseQueryTssPubkeyResponse();
    message.tssPubkey = (object.tssPubkey !== undefined && object.tssPubkey !== null)
      ? TssPubkey.fromPartial(object.tssPubkey)
      : undefined;
    return message;
  },
};

function createBaseQueryAllTssPubkeyRequest(): QueryAllTssPubkeyRequest {
  return { pagination: undefined };
}

export const QueryAllTssPubkeyRequest: MessageFns<QueryAllTssPubkeyRequest> = {
  encode(message: QueryAllTssPubkeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllTssPubkeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllTssPubkeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllTssPubkeyRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllTssPubkeyRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllTssPubkeyRequest>, I>>(base?: I): QueryAllTssPubkeyRequest {
    return QueryAllTssPubkeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllTssPubkeyRequest>, I>>(object: I): QueryAllTssPubkeyRequest {
    const message = createBaseQueryAllTssPubkeyRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryTssPubkeyAllResponse(): QueryTssPubkeyAllResponse {
  return { tssPubkey: [], pagination: undefined };
}

export const QueryTssPubkeyAllResponse: MessageFns<QueryTssPubkeyAllResponse> = {
  encode(message: QueryTssPubkeyAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tssPubkey) {
      TssPubkey.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryTssPubkeyAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryTssPubkeyAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.tssPubkey.push(TssPubkey.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryTssPubkeyAllResponse {
    return {
      tssPubkey: globalThis.Array.isArray(object?.tssPubkey)
        ? object.tssPubkey.map((e: any) => TssPubkey.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryTssPubkeyAllResponse): unknown {
    const obj: any = {};
    if (message.tssPubkey?.length) {
      obj.tssPubkey = message.tssPubkey.map((e) => TssPubkey.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryTssPubkeyAllResponse>, I>>(base?: I): QueryTssPubkeyAllResponse {
    return QueryTssPubkeyAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryTssPubkeyAllResponse>, I>>(object: I): QueryTssPubkeyAllResponse {
    const message = createBaseQueryTssPubkeyAllResponse();
    message.tssPubkey = object.tssPubkey?.map((e) => TssPubkey.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** Queries a list of Pubkey items. */
  Pubkey(request: QueryPubkeyRequest): Promise<QueryPubkeyResponse>;
  /** Queries all list of Pubkey items. */
  PubkeyAll(request: QueryAllPubkeyRequest): Promise<QueryPubkeyAllResponse>;
  /** Queries a list of GetKeygenBlock items. */
  GetKeygenBlock(request: QueryKeygenBlockRequest): Promise<KeygenBlock>;
  /** Queries a list of ListAllNewPubkey items. */
  ListAllNewPubkey(request: QueryListAllNewPubkeyRequest): Promise<QueryListAllNewPubkeyResponse>;
  /** Queries a list of TssPubkey items. */
  TssPubkey(request: QueryTssPubkeyRequest): Promise<QueryTssPubkeyResponse>;
  /** Queries all list of TssPubkey items. */
  TssPubkeyAll(request: QueryAllTssPubkeyRequest): Promise<QueryTssPubkeyAllResponse>;
}

export const QueryServiceName = "cfprotocol.tss.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.Pubkey = this.Pubkey.bind(this);
    this.PubkeyAll = this.PubkeyAll.bind(this);
    this.GetKeygenBlock = this.GetKeygenBlock.bind(this);
    this.ListAllNewPubkey = this.ListAllNewPubkey.bind(this);
    this.TssPubkey = this.TssPubkey.bind(this);
    this.TssPubkeyAll = this.TssPubkeyAll.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  Pubkey(request: QueryPubkeyRequest): Promise<QueryPubkeyResponse> {
    const data = QueryPubkeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Pubkey", data);
    return promise.then((data) => QueryPubkeyResponse.decode(new BinaryReader(data)));
  }

  PubkeyAll(request: QueryAllPubkeyRequest): Promise<QueryPubkeyAllResponse> {
    const data = QueryAllPubkeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PubkeyAll", data);
    return promise.then((data) => QueryPubkeyAllResponse.decode(new BinaryReader(data)));
  }

  GetKeygenBlock(request: QueryKeygenBlockRequest): Promise<KeygenBlock> {
    const data = QueryKeygenBlockRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetKeygenBlock", data);
    return promise.then((data) => KeygenBlock.decode(new BinaryReader(data)));
  }

  ListAllNewPubkey(request: QueryListAllNewPubkeyRequest): Promise<QueryListAllNewPubkeyResponse> {
    const data = QueryListAllNewPubkeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListAllNewPubkey", data);
    return promise.then((data) => QueryListAllNewPubkeyResponse.decode(new BinaryReader(data)));
  }

  TssPubkey(request: QueryTssPubkeyRequest): Promise<QueryTssPubkeyResponse> {
    const data = QueryTssPubkeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TssPubkey", data);
    return promise.then((data) => QueryTssPubkeyResponse.decode(new BinaryReader(data)));
  }

  TssPubkeyAll(request: QueryAllTssPubkeyRequest): Promise<QueryTssPubkeyAllResponse> {
    const data = QueryAllTssPubkeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TssPubkeyAll", data);
    return promise.then((data) => QueryTssPubkeyAllResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
