// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/lock/asset_lock_transaction.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.lock";

/** AssetLockTransaction defines the locking asset transaction data */
export interface AssetLockTransaction {
  id: number;
  /** asset profile id */
  assetId: number;
  senderAddress: string;
  /** the (compressed) public key of the sender */
  senderPubkey: Uint8Array;
  timestamp: string;
  amount: string;
  txHash: string;
  status: string;
  errReason: string;
  creator: string;
  lockAddress: string;
  pullStatus: string;
  /** the output index of the locked funds  in the HTLC creation transaction */
  creationVout: number;
}

function createBaseAssetLockTransaction(): AssetLockTransaction {
  return {
    id: 0,
    assetId: 0,
    senderAddress: "",
    senderPubkey: new Uint8Array(0),
    timestamp: "",
    amount: "",
    txHash: "",
    status: "",
    errReason: "",
    creator: "",
    lockAddress: "",
    pullStatus: "",
    creationVout: 0,
  };
}

export const AssetLockTransaction: MessageFns<AssetLockTransaction> = {
  encode(message: AssetLockTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.assetId !== 0) {
      writer.uint32(16).uint64(message.assetId);
    }
    if (message.senderAddress !== "") {
      writer.uint32(26).string(message.senderAddress);
    }
    if (message.senderPubkey.length !== 0) {
      writer.uint32(34).bytes(message.senderPubkey);
    }
    if (message.timestamp !== "") {
      writer.uint32(42).string(message.timestamp);
    }
    if (message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    if (message.txHash !== "") {
      writer.uint32(58).string(message.txHash);
    }
    if (message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    if (message.errReason !== "") {
      writer.uint32(74).string(message.errReason);
    }
    if (message.creator !== "") {
      writer.uint32(82).string(message.creator);
    }
    if (message.lockAddress !== "") {
      writer.uint32(90).string(message.lockAddress);
    }
    if (message.pullStatus !== "") {
      writer.uint32(98).string(message.pullStatus);
    }
    if (message.creationVout !== 0) {
      writer.uint32(104).uint64(message.creationVout);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetLockTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetLockTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.assetId = longToNumber(reader.uint64());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.senderAddress = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.senderPubkey = reader.bytes();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.txHash = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.errReason = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.lockAddress = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.pullStatus = reader.string();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.creationVout = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetLockTransaction {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      assetId: isSet(object.assetId) ? globalThis.Number(object.assetId) : 0,
      senderAddress: isSet(object.senderAddress) ? globalThis.String(object.senderAddress) : "",
      senderPubkey: isSet(object.senderPubkey) ? bytesFromBase64(object.senderPubkey) : new Uint8Array(0),
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      txHash: isSet(object.txHash) ? globalThis.String(object.txHash) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      errReason: isSet(object.errReason) ? globalThis.String(object.errReason) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      lockAddress: isSet(object.lockAddress) ? globalThis.String(object.lockAddress) : "",
      pullStatus: isSet(object.pullStatus) ? globalThis.String(object.pullStatus) : "",
      creationVout: isSet(object.creationVout) ? globalThis.Number(object.creationVout) : 0,
    };
  },

  toJSON(message: AssetLockTransaction): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.assetId !== 0) {
      obj.assetId = Math.round(message.assetId);
    }
    if (message.senderAddress !== "") {
      obj.senderAddress = message.senderAddress;
    }
    if (message.senderPubkey.length !== 0) {
      obj.senderPubkey = base64FromBytes(message.senderPubkey);
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.errReason !== "") {
      obj.errReason = message.errReason;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.lockAddress !== "") {
      obj.lockAddress = message.lockAddress;
    }
    if (message.pullStatus !== "") {
      obj.pullStatus = message.pullStatus;
    }
    if (message.creationVout !== 0) {
      obj.creationVout = Math.round(message.creationVout);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetLockTransaction>, I>>(base?: I): AssetLockTransaction {
    return AssetLockTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetLockTransaction>, I>>(object: I): AssetLockTransaction {
    const message = createBaseAssetLockTransaction();
    message.id = object.id ?? 0;
    message.assetId = object.assetId ?? 0;
    message.senderAddress = object.senderAddress ?? "";
    message.senderPubkey = object.senderPubkey ?? new Uint8Array(0);
    message.timestamp = object.timestamp ?? "";
    message.amount = object.amount ?? "";
    message.txHash = object.txHash ?? "";
    message.status = object.status ?? "";
    message.errReason = object.errReason ?? "";
    message.creator = object.creator ?? "";
    message.lockAddress = object.lockAddress ?? "";
    message.pullStatus = object.pullStatus ?? "";
    message.creationVout = object.creationVout ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
