// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/asset/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../cosmos/base/query/v1beta1/pagination";
import { Params } from "./params";
import { AssetProfile } from "./profile";

export const protobufPackage = "cfprotocol.asset";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryAssetProfileRequest is request type for the Query/asset_profile/{id} RPC method. */
export interface QueryAssetProfileRequest {
  id: number;
}

/** QueryAssetProfileResponse is response type for the Query/asset_profile/{id} RPC method. */
export interface QueryAssetProfileResponse {
  assetProfile: AssetProfile | undefined;
}

/** QueryAssetProfileAllRequest is request type for the Query/asset_profile RPC method. */
export interface QueryAssetProfileAllRequest {
  pagination: PageRequest | undefined;
}

/** QueryAssetProfileAllResponse is response type for the Query/asset_profile RPC method. */
export interface QueryAssetProfileAllResponse {
  assetProfile: AssetProfile[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryAssetProfileRequest(): QueryAssetProfileRequest {
  return { id: 0 };
}

export const QueryAssetProfileRequest: MessageFns<QueryAssetProfileRequest> = {
  encode(message: QueryAssetProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAssetProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAssetProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAssetProfileRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryAssetProfileRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAssetProfileRequest>, I>>(base?: I): QueryAssetProfileRequest {
    return QueryAssetProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAssetProfileRequest>, I>>(object: I): QueryAssetProfileRequest {
    const message = createBaseQueryAssetProfileRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryAssetProfileResponse(): QueryAssetProfileResponse {
  return { assetProfile: undefined };
}

export const QueryAssetProfileResponse: MessageFns<QueryAssetProfileResponse> = {
  encode(message: QueryAssetProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetProfile !== undefined) {
      AssetProfile.encode(message.assetProfile, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAssetProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAssetProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.assetProfile = AssetProfile.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAssetProfileResponse {
    return { assetProfile: isSet(object.assetProfile) ? AssetProfile.fromJSON(object.assetProfile) : undefined };
  },

  toJSON(message: QueryAssetProfileResponse): unknown {
    const obj: any = {};
    if (message.assetProfile !== undefined) {
      obj.assetProfile = AssetProfile.toJSON(message.assetProfile);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAssetProfileResponse>, I>>(base?: I): QueryAssetProfileResponse {
    return QueryAssetProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAssetProfileResponse>, I>>(object: I): QueryAssetProfileResponse {
    const message = createBaseQueryAssetProfileResponse();
    message.assetProfile = (object.assetProfile !== undefined && object.assetProfile !== null)
      ? AssetProfile.fromPartial(object.assetProfile)
      : undefined;
    return message;
  },
};

function createBaseQueryAssetProfileAllRequest(): QueryAssetProfileAllRequest {
  return { pagination: undefined };
}

export const QueryAssetProfileAllRequest: MessageFns<QueryAssetProfileAllRequest> = {
  encode(message: QueryAssetProfileAllRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAssetProfileAllRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAssetProfileAllRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAssetProfileAllRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAssetProfileAllRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAssetProfileAllRequest>, I>>(base?: I): QueryAssetProfileAllRequest {
    return QueryAssetProfileAllRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAssetProfileAllRequest>, I>>(object: I): QueryAssetProfileAllRequest {
    const message = createBaseQueryAssetProfileAllRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAssetProfileAllResponse(): QueryAssetProfileAllResponse {
  return { assetProfile: [], pagination: undefined };
}

export const QueryAssetProfileAllResponse: MessageFns<QueryAssetProfileAllResponse> = {
  encode(message: QueryAssetProfileAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.assetProfile) {
      AssetProfile.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAssetProfileAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAssetProfileAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.assetProfile.push(AssetProfile.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAssetProfileAllResponse {
    return {
      assetProfile: globalThis.Array.isArray(object?.assetProfile)
        ? object.assetProfile.map((e: any) => AssetProfile.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAssetProfileAllResponse): unknown {
    const obj: any = {};
    if (message.assetProfile?.length) {
      obj.assetProfile = message.assetProfile.map((e) => AssetProfile.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAssetProfileAllResponse>, I>>(base?: I): QueryAssetProfileAllResponse {
    return QueryAssetProfileAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAssetProfileAllResponse>, I>>(object: I): QueryAssetProfileAllResponse {
    const message = createBaseQueryAssetProfileAllResponse();
    message.assetProfile = object.assetProfile?.map((e) => AssetProfile.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** Queries a list of AssetProfile items. */
  AssetProfile(request: QueryAssetProfileRequest): Promise<QueryAssetProfileResponse>;
  /** Queries all list of AssetProfile items. */
  AssetProfileAll(request: QueryAssetProfileAllRequest): Promise<QueryAssetProfileAllResponse>;
}

export const QueryServiceName = "cfprotocol.asset.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.AssetProfile = this.AssetProfile.bind(this);
    this.AssetProfileAll = this.AssetProfileAll.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  AssetProfile(request: QueryAssetProfileRequest): Promise<QueryAssetProfileResponse> {
    const data = QueryAssetProfileRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AssetProfile", data);
    return promise.then((data) => QueryAssetProfileResponse.decode(new BinaryReader(data)));
  }

  AssetProfileAll(request: QueryAssetProfileAllRequest): Promise<QueryAssetProfileAllResponse> {
    const data = QueryAssetProfileAllRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AssetProfileAll", data);
    return promise.then((data) => QueryAssetProfileAllResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
