// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/account_summary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.loan";

/** AccountSummary defines account details */
export interface AccountSummary {
  user: string;
  netApy: string;
  dailyEarnings: string;
  totalSupply: string;
  totalBorrow: string;
  totalStaked: string;
  borrowLimitUsed: string;
  safeLimit: string;
  reserved: string;
}

function createBaseAccountSummary(): AccountSummary {
  return {
    user: "",
    netApy: "",
    dailyEarnings: "",
    totalSupply: "",
    totalBorrow: "",
    totalStaked: "",
    borrowLimitUsed: "",
    safeLimit: "",
    reserved: "",
  };
}

export const AccountSummary: MessageFns<AccountSummary> = {
  encode(message: AccountSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    if (message.netApy !== "") {
      writer.uint32(18).string(message.netApy);
    }
    if (message.dailyEarnings !== "") {
      writer.uint32(26).string(message.dailyEarnings);
    }
    if (message.totalSupply !== "") {
      writer.uint32(34).string(message.totalSupply);
    }
    if (message.totalBorrow !== "") {
      writer.uint32(42).string(message.totalBorrow);
    }
    if (message.totalStaked !== "") {
      writer.uint32(50).string(message.totalStaked);
    }
    if (message.borrowLimitUsed !== "") {
      writer.uint32(58).string(message.borrowLimitUsed);
    }
    if (message.safeLimit !== "") {
      writer.uint32(66).string(message.safeLimit);
    }
    if (message.reserved !== "") {
      writer.uint32(74).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.netApy = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.dailyEarnings = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.totalSupply = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.totalBorrow = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.totalStaked = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.borrowLimitUsed = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.safeLimit = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountSummary {
    return {
      user: isSet(object.user) ? globalThis.String(object.user) : "",
      netApy: isSet(object.netApy) ? globalThis.String(object.netApy) : "",
      dailyEarnings: isSet(object.dailyEarnings) ? globalThis.String(object.dailyEarnings) : "",
      totalSupply: isSet(object.totalSupply) ? globalThis.String(object.totalSupply) : "",
      totalBorrow: isSet(object.totalBorrow) ? globalThis.String(object.totalBorrow) : "",
      totalStaked: isSet(object.totalStaked) ? globalThis.String(object.totalStaked) : "",
      borrowLimitUsed: isSet(object.borrowLimitUsed) ? globalThis.String(object.borrowLimitUsed) : "",
      safeLimit: isSet(object.safeLimit) ? globalThis.String(object.safeLimit) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: AccountSummary): unknown {
    const obj: any = {};
    if (message.user !== "") {
      obj.user = message.user;
    }
    if (message.netApy !== "") {
      obj.netApy = message.netApy;
    }
    if (message.dailyEarnings !== "") {
      obj.dailyEarnings = message.dailyEarnings;
    }
    if (message.totalSupply !== "") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.totalBorrow !== "") {
      obj.totalBorrow = message.totalBorrow;
    }
    if (message.totalStaked !== "") {
      obj.totalStaked = message.totalStaked;
    }
    if (message.borrowLimitUsed !== "") {
      obj.borrowLimitUsed = message.borrowLimitUsed;
    }
    if (message.safeLimit !== "") {
      obj.safeLimit = message.safeLimit;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountSummary>, I>>(base?: I): AccountSummary {
    return AccountSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountSummary>, I>>(object: I): AccountSummary {
    const message = createBaseAccountSummary();
    message.user = object.user ?? "";
    message.netApy = object.netApy ?? "";
    message.dailyEarnings = object.dailyEarnings ?? "";
    message.totalSupply = object.totalSupply ?? "";
    message.totalBorrow = object.totalBorrow ?? "";
    message.totalStaked = object.totalStaked ?? "";
    message.borrowLimitUsed = object.borrowLimitUsed ?? "";
    message.safeLimit = object.safeLimit ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
