// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/tss/tss_pubkey.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.tss";

/** TssPubkey defines the tss result data */
export interface TssPubkey {
  id: number;
  tssPubkey: string;
  ecdsa: string;
  bitcoin: string;
  reserved: string;
}

function createBaseTssPubkey(): TssPubkey {
  return { id: 0, tssPubkey: "", ecdsa: "", bitcoin: "", reserved: "" };
}

export const TssPubkey: MessageFns<TssPubkey> = {
  encode(message: TssPubkey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.tssPubkey !== "") {
      writer.uint32(18).string(message.tssPubkey);
    }
    if (message.ecdsa !== "") {
      writer.uint32(26).string(message.ecdsa);
    }
    if (message.bitcoin !== "") {
      writer.uint32(34).string(message.bitcoin);
    }
    if (message.reserved !== "") {
      writer.uint32(42).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TssPubkey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTssPubkey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.tssPubkey = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.ecdsa = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.bitcoin = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TssPubkey {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      tssPubkey: isSet(object.tssPubkey) ? globalThis.String(object.tssPubkey) : "",
      ecdsa: isSet(object.ecdsa) ? globalThis.String(object.ecdsa) : "",
      bitcoin: isSet(object.bitcoin) ? globalThis.String(object.bitcoin) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: TssPubkey): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.tssPubkey !== "") {
      obj.tssPubkey = message.tssPubkey;
    }
    if (message.ecdsa !== "") {
      obj.ecdsa = message.ecdsa;
    }
    if (message.bitcoin !== "") {
      obj.bitcoin = message.bitcoin;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TssPubkey>, I>>(base?: I): TssPubkey {
    return TssPubkey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TssPubkey>, I>>(object: I): TssPubkey {
    const message = createBaseTssPubkey();
    message.id = object.id ?? 0;
    message.tssPubkey = object.tssPubkey ?? "";
    message.ecdsa = object.ecdsa ?? "";
    message.bitcoin = object.bitcoin ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
