// @ts-nocheck
// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { Balance } from "./types/cfprotocol/chain/pool_balance";
import { MsgRemoveChain } from "./types/cfprotocol/chain/tx";
import { GenesisState } from "./types/cfprotocol/chain/genesis";
import { GovSummary } from "./types/cfprotocol/chain/gov_summary";
import { QueryParamsRequest } from "./types/cfprotocol/chain/query";
import { Chain } from "./types/cfprotocol/chain/chain";
import { MsgUpdateBalanceResponse } from "./types/cfprotocol/chain/tx";
import { Params } from "./types/cfprotocol/chain/params";
import { MsgUpdateNativeBalance } from "./types/cfprotocol/chain/tx";
import { QueryParamsResponse } from "./types/cfprotocol/chain/query";
import { QueryChainAllRequest } from "./types/cfprotocol/chain/query";
import { QueryBalanceObservationAllRequest } from "./types/cfprotocol/chain/query";
import { QueryGetStakeSummaryRequest } from "./types/cfprotocol/chain/query";
import { QueryGetStakeSummaryResponse } from "./types/cfprotocol/chain/query";
import { MsgAddChainResponse } from "./types/cfprotocol/chain/tx";
import { MsgRemoveTokenResponse } from "./types/cfprotocol/chain/tx";
import { MsgAddTokenResponse } from "./types/cfprotocol/chain/tx";
import { MsgAddToken } from "./types/cfprotocol/chain/tx";
import { QueryChainAllResponse } from "./types/cfprotocol/chain/query";
import { QueryPoolBalanceResponse } from "./types/cfprotocol/chain/query";
import { QueryBalanceObservationRequest } from "./types/cfprotocol/chain/query";
import { QueryBalanceObservationResponse } from "./types/cfprotocol/chain/query";
import { QueryPoolBalanceAllRequest } from "./types/cfprotocol/chain/query";
import { QueryPoolBalanceAllResponse } from "./types/cfprotocol/chain/query";
import { MsgUpdateNativeBalanceResponse } from "./types/cfprotocol/chain/tx";
import { MsgAddChain } from "./types/cfprotocol/chain/tx";
import { BalanceObservation } from "./types/cfprotocol/chain/balance_observation";
import { QueryPoolBalanceRequest } from "./types/cfprotocol/chain/query";
import { QueryBalanceObservationAllResponse } from "./types/cfprotocol/chain/query";
import { QueryGetGovSummaryRequest } from "./types/cfprotocol/chain/query";
import { MsgUpdateParams } from "./types/cfprotocol/chain/tx";
import { MsgUpdateParamsResponse } from "./types/cfprotocol/chain/tx";
import { MsgRemoveToken } from "./types/cfprotocol/chain/tx";
import { QueryChainRequest } from "./types/cfprotocol/chain/query";
import { QueryChainResponse } from "./types/cfprotocol/chain/query";
import { MsgUpdateBalance } from "./types/cfprotocol/chain/tx";
import { PoolBalance } from "./types/cfprotocol/chain/pool_balance";
import { QueryGetGovSummaryResponse } from "./types/cfprotocol/chain/query";
import { StakeSummary } from "./types/cfprotocol/chain/stake_summary";
import { MsgRemoveChainResponse } from "./types/cfprotocol/chain/tx";


export { Balance, MsgRemoveChain, GenesisState, GovSummary, QueryParamsRequest, Chain, MsgUpdateBalanceResponse, Params, MsgUpdateNativeBalance, QueryParamsResponse, QueryChainAllRequest, QueryBalanceObservationAllRequest, QueryGetStakeSummaryRequest, QueryGetStakeSummaryResponse, MsgAddChainResponse, MsgRemoveTokenResponse, MsgAddTokenResponse, MsgAddToken, QueryChainAllResponse, QueryPoolBalanceResponse, QueryBalanceObservationRequest, QueryBalanceObservationResponse, QueryPoolBalanceAllRequest, QueryPoolBalanceAllResponse, MsgUpdateNativeBalanceResponse, MsgAddChain, BalanceObservation, QueryPoolBalanceRequest, QueryBalanceObservationAllResponse, QueryGetGovSummaryRequest, MsgUpdateParams, MsgUpdateParamsResponse, MsgRemoveToken, QueryChainRequest, QueryChainResponse, MsgUpdateBalance, PoolBalance, QueryGetGovSummaryResponse, StakeSummary, MsgRemoveChainResponse };

type sendBalanceParams = {
  value: Balance,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveChainParams = {
  value: MsgRemoveChain,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendGovSummaryParams = {
  value: GovSummary,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendChainParams = {
  value: Chain,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateBalanceResponseParams = {
  value: MsgUpdateBalanceResponse,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateNativeBalanceParams = {
  value: MsgUpdateNativeBalance,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryChainAllRequestParams = {
  value: QueryChainAllRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryBalanceObservationAllRequestParams = {
  value: QueryBalanceObservationAllRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetStakeSummaryRequestParams = {
  value: QueryGetStakeSummaryRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetStakeSummaryResponseParams = {
  value: QueryGetStakeSummaryResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddChainResponseParams = {
  value: MsgAddChainResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveTokenResponseParams = {
  value: MsgRemoveTokenResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddTokenResponseParams = {
  value: MsgAddTokenResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddTokenParams = {
  value: MsgAddToken,
  fee?: StdFee,
  memo?: string
};

type sendQueryChainAllResponseParams = {
  value: QueryChainAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryPoolBalanceResponseParams = {
  value: QueryPoolBalanceResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryBalanceObservationRequestParams = {
  value: QueryBalanceObservationRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryBalanceObservationResponseParams = {
  value: QueryBalanceObservationResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryPoolBalanceAllRequestParams = {
  value: QueryPoolBalanceAllRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryPoolBalanceAllResponseParams = {
  value: QueryPoolBalanceAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateNativeBalanceResponseParams = {
  value: MsgUpdateNativeBalanceResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddChainParams = {
  value: MsgAddChain,
  fee?: StdFee,
  memo?: string
};

type sendBalanceObservationParams = {
  value: BalanceObservation,
  fee?: StdFee,
  memo?: string
};

type sendQueryPoolBalanceRequestParams = {
  value: QueryPoolBalanceRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryBalanceObservationAllResponseParams = {
  value: QueryBalanceObservationAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetGovSummaryRequestParams = {
  value: QueryGetGovSummaryRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveTokenParams = {
  value: MsgRemoveToken,
  fee?: StdFee,
  memo?: string
};

type sendQueryChainRequestParams = {
  value: QueryChainRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryChainResponseParams = {
  value: QueryChainResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateBalanceParams = {
  value: MsgUpdateBalance,
  fee?: StdFee,
  memo?: string
};

type sendPoolBalanceParams = {
  value: PoolBalance,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetGovSummaryResponseParams = {
  value: QueryGetGovSummaryResponse,
  fee?: StdFee,
  memo?: string
};

type sendStakeSummaryParams = {
  value: StakeSummary,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveChainResponseParams = {
  value: MsgRemoveChainResponse,
  fee?: StdFee,
  memo?: string
};


type balanceParams = {
  value: Balance,
};

type msgRemoveChainParams = {
  value: MsgRemoveChain,
};

type genesisStateParams = {
  value: GenesisState,
};

type govSummaryParams = {
  value: GovSummary,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type chainParams = {
  value: Chain,
};

type msgUpdateBalanceResponseParams = {
  value: MsgUpdateBalanceResponse,
};

type paramsParams = {
  value: Params,
};

type msgUpdateNativeBalanceParams = {
  value: MsgUpdateNativeBalance,
};

type queryParamsResponseParams = {
  value: QueryParamsResponse,
};

type queryChainAllRequestParams = {
  value: QueryChainAllRequest,
};

type queryBalanceObservationAllRequestParams = {
  value: QueryBalanceObservationAllRequest,
};

type queryGetStakeSummaryRequestParams = {
  value: QueryGetStakeSummaryRequest,
};

type queryGetStakeSummaryResponseParams = {
  value: QueryGetStakeSummaryResponse,
};

type msgAddChainResponseParams = {
  value: MsgAddChainResponse,
};

type msgRemoveTokenResponseParams = {
  value: MsgRemoveTokenResponse,
};

type msgAddTokenResponseParams = {
  value: MsgAddTokenResponse,
};

type msgAddTokenParams = {
  value: MsgAddToken,
};

type queryChainAllResponseParams = {
  value: QueryChainAllResponse,
};

type queryPoolBalanceResponseParams = {
  value: QueryPoolBalanceResponse,
};

type queryBalanceObservationRequestParams = {
  value: QueryBalanceObservationRequest,
};

type queryBalanceObservationResponseParams = {
  value: QueryBalanceObservationResponse,
};

type queryPoolBalanceAllRequestParams = {
  value: QueryPoolBalanceAllRequest,
};

type queryPoolBalanceAllResponseParams = {
  value: QueryPoolBalanceAllResponse,
};

type msgUpdateNativeBalanceResponseParams = {
  value: MsgUpdateNativeBalanceResponse,
};

type msgAddChainParams = {
  value: MsgAddChain,
};

type balanceObservationParams = {
  value: BalanceObservation,
};

type queryPoolBalanceRequestParams = {
  value: QueryPoolBalanceRequest,
};

type queryBalanceObservationAllResponseParams = {
  value: QueryBalanceObservationAllResponse,
};

type queryGetGovSummaryRequestParams = {
  value: QueryGetGovSummaryRequest,
};

type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type msgRemoveTokenParams = {
  value: MsgRemoveToken,
};

type queryChainRequestParams = {
  value: QueryChainRequest,
};

type queryChainResponseParams = {
  value: QueryChainResponse,
};

type msgUpdateBalanceParams = {
  value: MsgUpdateBalance,
};

type poolBalanceParams = {
  value: PoolBalance,
};

type queryGetGovSummaryResponseParams = {
  value: QueryGetGovSummaryResponse,
};

type stakeSummaryParams = {
  value: StakeSummary,
};

type msgRemoveChainResponseParams = {
  value: MsgRemoveChainResponse,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendBalance({ value, fee, memo }: sendBalanceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendBalance: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.balance({ value: Balance.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendBalance: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveChain({ value, fee, memo }: sendMsgRemoveChainParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveChain: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveChain({ value: MsgRemoveChain.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveChain: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGovSummary({ value, fee, memo }: sendGovSummaryParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGovSummary: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.govSummary({ value: GovSummary.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGovSummary: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendChain({ value, fee, memo }: sendChainParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendChain: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.chain({ value: Chain.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendChain: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateBalanceResponse({ value, fee, memo }: sendMsgUpdateBalanceResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateBalanceResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateBalanceResponse({ value: MsgUpdateBalanceResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateBalanceResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateNativeBalance({ value, fee, memo }: sendMsgUpdateNativeBalanceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateNativeBalance: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateNativeBalance({ value: MsgUpdateNativeBalance.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateNativeBalance: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryChainAllRequest({ value, fee, memo }: sendQueryChainAllRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryChainAllRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryChainAllRequest({ value: QueryChainAllRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryChainAllRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryBalanceObservationAllRequest({ value, fee, memo }: sendQueryBalanceObservationAllRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryBalanceObservationAllRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryBalanceObservationAllRequest({ value: QueryBalanceObservationAllRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryBalanceObservationAllRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetStakeSummaryRequest({ value, fee, memo }: sendQueryGetStakeSummaryRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetStakeSummaryRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetStakeSummaryRequest({ value: QueryGetStakeSummaryRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetStakeSummaryRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetStakeSummaryResponse({ value, fee, memo }: sendQueryGetStakeSummaryResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetStakeSummaryResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetStakeSummaryResponse({ value: QueryGetStakeSummaryResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetStakeSummaryResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddChainResponse({ value, fee, memo }: sendMsgAddChainResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddChainResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddChainResponse({ value: MsgAddChainResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddChainResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveTokenResponse({ value, fee, memo }: sendMsgRemoveTokenResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveTokenResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveTokenResponse({ value: MsgRemoveTokenResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveTokenResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddTokenResponse({ value, fee, memo }: sendMsgAddTokenResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddTokenResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddTokenResponse({ value: MsgAddTokenResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddTokenResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddToken({ value, fee, memo }: sendMsgAddTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddToken({ value: MsgAddToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryChainAllResponse({ value, fee, memo }: sendQueryChainAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryChainAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryChainAllResponse({ value: QueryChainAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryChainAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryPoolBalanceResponse({ value, fee, memo }: sendQueryPoolBalanceResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryPoolBalanceResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryPoolBalanceResponse({ value: QueryPoolBalanceResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryPoolBalanceResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryBalanceObservationRequest({ value, fee, memo }: sendQueryBalanceObservationRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryBalanceObservationRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryBalanceObservationRequest({ value: QueryBalanceObservationRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryBalanceObservationRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryBalanceObservationResponse({ value, fee, memo }: sendQueryBalanceObservationResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryBalanceObservationResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryBalanceObservationResponse({ value: QueryBalanceObservationResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryBalanceObservationResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryPoolBalanceAllRequest({ value, fee, memo }: sendQueryPoolBalanceAllRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryPoolBalanceAllRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryPoolBalanceAllRequest({ value: QueryPoolBalanceAllRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryPoolBalanceAllRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryPoolBalanceAllResponse({ value, fee, memo }: sendQueryPoolBalanceAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryPoolBalanceAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryPoolBalanceAllResponse({ value: QueryPoolBalanceAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryPoolBalanceAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateNativeBalanceResponse({ value, fee, memo }: sendMsgUpdateNativeBalanceResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateNativeBalanceResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateNativeBalanceResponse({ value: MsgUpdateNativeBalanceResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateNativeBalanceResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddChain({ value, fee, memo }: sendMsgAddChainParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddChain: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddChain({ value: MsgAddChain.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddChain: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendBalanceObservation({ value, fee, memo }: sendBalanceObservationParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendBalanceObservation: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.balanceObservation({ value: BalanceObservation.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendBalanceObservation: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryPoolBalanceRequest({ value, fee, memo }: sendQueryPoolBalanceRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryPoolBalanceRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryPoolBalanceRequest({ value: QueryPoolBalanceRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryPoolBalanceRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryBalanceObservationAllResponse({ value, fee, memo }: sendQueryBalanceObservationAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryBalanceObservationAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryBalanceObservationAllResponse({ value: QueryBalanceObservationAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryBalanceObservationAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetGovSummaryRequest({ value, fee, memo }: sendQueryGetGovSummaryRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetGovSummaryRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetGovSummaryRequest({ value: QueryGetGovSummaryRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetGovSummaryRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveToken({ value, fee, memo }: sendMsgRemoveTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveToken({ value: MsgRemoveToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryChainRequest({ value, fee, memo }: sendQueryChainRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryChainRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryChainRequest({ value: QueryChainRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryChainRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryChainResponse({ value, fee, memo }: sendQueryChainResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryChainResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryChainResponse({ value: QueryChainResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryChainResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateBalance({ value, fee, memo }: sendMsgUpdateBalanceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateBalance: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateBalance({ value: MsgUpdateBalance.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateBalance: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPoolBalance({ value, fee, memo }: sendPoolBalanceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPoolBalance: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.poolBalance({ value: PoolBalance.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPoolBalance: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetGovSummaryResponse({ value, fee, memo }: sendQueryGetGovSummaryResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetGovSummaryResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetGovSummaryResponse({ value: QueryGetGovSummaryResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetGovSummaryResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendStakeSummary({ value, fee, memo }: sendStakeSummaryParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendStakeSummary: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.stakeSummary({ value: StakeSummary.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendStakeSummary: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveChainResponse({ value, fee, memo }: sendMsgRemoveChainResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveChainResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRemoveChainResponse({ value: MsgRemoveChainResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveChainResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		balance({ value }: balanceParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.Balance", value: Balance.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Balance: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveChain({ value }: msgRemoveChainParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgRemoveChain", value: MsgRemoveChain.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveChain: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		govSummary({ value }: govSummaryParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.GovSummary", value: GovSummary.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GovSummary: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		chain({ value }: chainParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.Chain", value: Chain.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Chain: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateBalanceResponse({ value }: msgUpdateBalanceResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateBalanceResponse", value: MsgUpdateBalanceResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateBalanceResponse: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateNativeBalance({ value }: msgUpdateNativeBalanceParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateNativeBalance", value: MsgUpdateNativeBalance.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateNativeBalance: Could not create message: ' + e.message)
			}
		},
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		queryChainAllRequest({ value }: queryChainAllRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryChainAllRequest", value: QueryChainAllRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryChainAllRequest: Could not create message: ' + e.message)
			}
		},
		
		queryBalanceObservationAllRequest({ value }: queryBalanceObservationAllRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryBalanceObservationAllRequest", value: QueryBalanceObservationAllRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryBalanceObservationAllRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetStakeSummaryRequest({ value }: queryGetStakeSummaryRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryGetStakeSummaryRequest", value: QueryGetStakeSummaryRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetStakeSummaryRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetStakeSummaryResponse({ value }: queryGetStakeSummaryResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryGetStakeSummaryResponse", value: QueryGetStakeSummaryResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetStakeSummaryResponse: Could not create message: ' + e.message)
			}
		},
		
		msgAddChainResponse({ value }: msgAddChainResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgAddChainResponse", value: MsgAddChainResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddChainResponse: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveTokenResponse({ value }: msgRemoveTokenResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgRemoveTokenResponse", value: MsgRemoveTokenResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveTokenResponse: Could not create message: ' + e.message)
			}
		},
		
		msgAddTokenResponse({ value }: msgAddTokenResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgAddTokenResponse", value: MsgAddTokenResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddTokenResponse: Could not create message: ' + e.message)
			}
		},
		
		msgAddToken({ value }: msgAddTokenParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgAddToken", value: MsgAddToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddToken: Could not create message: ' + e.message)
			}
		},
		
		queryChainAllResponse({ value }: queryChainAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryChainAllResponse", value: QueryChainAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryChainAllResponse: Could not create message: ' + e.message)
			}
		},
		
		queryPoolBalanceResponse({ value }: queryPoolBalanceResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryPoolBalanceResponse", value: QueryPoolBalanceResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryPoolBalanceResponse: Could not create message: ' + e.message)
			}
		},
		
		queryBalanceObservationRequest({ value }: queryBalanceObservationRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryBalanceObservationRequest", value: QueryBalanceObservationRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryBalanceObservationRequest: Could not create message: ' + e.message)
			}
		},
		
		queryBalanceObservationResponse({ value }: queryBalanceObservationResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryBalanceObservationResponse", value: QueryBalanceObservationResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryBalanceObservationResponse: Could not create message: ' + e.message)
			}
		},
		
		queryPoolBalanceAllRequest({ value }: queryPoolBalanceAllRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryPoolBalanceAllRequest", value: QueryPoolBalanceAllRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryPoolBalanceAllRequest: Could not create message: ' + e.message)
			}
		},
		
		queryPoolBalanceAllResponse({ value }: queryPoolBalanceAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryPoolBalanceAllResponse", value: QueryPoolBalanceAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryPoolBalanceAllResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateNativeBalanceResponse({ value }: msgUpdateNativeBalanceResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateNativeBalanceResponse", value: MsgUpdateNativeBalanceResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateNativeBalanceResponse: Could not create message: ' + e.message)
			}
		},
		
		msgAddChain({ value }: msgAddChainParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgAddChain", value: MsgAddChain.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddChain: Could not create message: ' + e.message)
			}
		},
		
		balanceObservation({ value }: balanceObservationParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.BalanceObservation", value: BalanceObservation.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:BalanceObservation: Could not create message: ' + e.message)
			}
		},
		
		queryPoolBalanceRequest({ value }: queryPoolBalanceRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryPoolBalanceRequest", value: QueryPoolBalanceRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryPoolBalanceRequest: Could not create message: ' + e.message)
			}
		},
		
		queryBalanceObservationAllResponse({ value }: queryBalanceObservationAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryBalanceObservationAllResponse", value: QueryBalanceObservationAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryBalanceObservationAllResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetGovSummaryRequest({ value }: queryGetGovSummaryRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryGetGovSummaryRequest", value: QueryGetGovSummaryRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetGovSummaryRequest: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveToken({ value }: msgRemoveTokenParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgRemoveToken", value: MsgRemoveToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveToken: Could not create message: ' + e.message)
			}
		},
		
		queryChainRequest({ value }: queryChainRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryChainRequest", value: QueryChainRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryChainRequest: Could not create message: ' + e.message)
			}
		},
		
		queryChainResponse({ value }: queryChainResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryChainResponse", value: QueryChainResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryChainResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateBalance({ value }: msgUpdateBalanceParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgUpdateBalance", value: MsgUpdateBalance.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateBalance: Could not create message: ' + e.message)
			}
		},
		
		poolBalance({ value }: poolBalanceParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.PoolBalance", value: PoolBalance.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:PoolBalance: Could not create message: ' + e.message)
			}
		},
		
		queryGetGovSummaryResponse({ value }: queryGetGovSummaryResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.QueryGetGovSummaryResponse", value: QueryGetGovSummaryResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetGovSummaryResponse: Could not create message: ' + e.message)
			}
		},
		
		stakeSummary({ value }: stakeSummaryParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.StakeSummary", value: StakeSummary.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:StakeSummary: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveChainResponse({ value }: msgRemoveChainResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.chain.MsgRemoveChainResponse", value: MsgRemoveChainResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveChainResponse: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			CfprotocolChain: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;