// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/chain/gov_summary.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.chain";

/** GovSummary defines the summary of the staking information */
export interface GovSummary {
  totalProposals: number;
  totalStaked: string;
}

function createBaseGovSummary(): GovSummary {
  return { totalProposals: 0, totalStaked: "" };
}

export const GovSummary: MessageFns<GovSummary> = {
  encode(message: GovSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalProposals !== 0) {
      writer.uint32(8).uint64(message.totalProposals);
    }
    if (message.totalStaked !== "") {
      writer.uint32(18).string(message.totalStaked);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GovSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGovSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.totalProposals = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.totalStaked = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GovSummary {
    return {
      totalProposals: isSet(object.totalProposals) ? globalThis.Number(object.totalProposals) : 0,
      totalStaked: isSet(object.totalStaked) ? globalThis.String(object.totalStaked) : "",
    };
  },

  toJSON(message: GovSummary): unknown {
    const obj: any = {};
    if (message.totalProposals !== 0) {
      obj.totalProposals = Math.round(message.totalProposals);
    }
    if (message.totalStaked !== "") {
      obj.totalStaked = message.totalStaked;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GovSummary>, I>>(base?: I): GovSummary {
    return GovSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GovSummary>, I>>(object: I): GovSummary {
    const message = createBaseGovSummary();
    message.totalProposals = object.totalProposals ?? 0;
    message.totalStaked = object.totalStaked ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
