// @ts-nocheck
// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
// import { Api } from "./rest";
import { MsgRequestLoanResponse } from "./types/cfprotocol/loan/tx";
import { QueryAllObserveVoteRequest } from "./types/cfprotocol/loan/query";
import { ObserveVoteAllResponse } from "./types/cfprotocol/loan/query";
import { ObserveVoteResponse } from "./types/cfprotocol/loan/query";
import { QueryGetLoanEntityResponse } from "./types/cfprotocol/loan/query";
import { QueryGetAccountSummaryResponse } from "./types/cfprotocol/loan/query";
import { PoolSummary } from "./types/cfprotocol/loan/pool_summary";
import { MsgUpdateParamsResponse } from "./types/cfprotocol/loan/tx";
import { AssetBorrowed } from "./types/cfprotocol/loan/asset_borrowed";
import { QueryAllLoanTransactionRequest } from "./types/cfprotocol/loan/query";
import { QueryGetPoolListRequest } from "./types/cfprotocol/loan/query";
import { QueryGetLoanObservationRequest } from "./types/cfprotocol/loan/query";
import { MsgObservationVoteResponse } from "./types/cfprotocol/loan/tx";
import { AssetSupplied } from "./types/cfprotocol/loan/asset_supplied";
import { QueryGetLoanTransactionRequest } from "./types/cfprotocol/loan/query";
import { QueryGetAvailableTransactionRequest } from "./types/cfprotocol/loan/query";
import { LoanObservation } from "./types/cfprotocol/loan/loan_observation";
import { MsgVoteLoanTransaction } from "./types/cfprotocol/loan/tx";
import { QueryParamsRequest } from "./types/cfprotocol/loan/query";
import { LoanTransactionAllResponse } from "./types/cfprotocol/loan/query";
import { QueryGetAccountBorrowedAssetsRequest } from "./types/cfprotocol/loan/query";
import { QueryGetPoolListResponse } from "./types/cfprotocol/loan/query";
import { Params } from "./types/cfprotocol/loan/params";
import { MsgVoteLoanTransactionResponse } from "./types/cfprotocol/loan/tx";
import { QueryGetLoanEntityRequest } from "./types/cfprotocol/loan/query";
import { QueryGetAccountSummaryRequest } from "./types/cfprotocol/loan/query";
import { LoanTransaction } from "./types/cfprotocol/loan/transaction";
import { LoanEntity } from "./types/cfprotocol/loan/loan_entity";
import { QueryGetPoolSummaryResponse } from "./types/cfprotocol/loan/query";
import { AssetPool } from "./types/cfprotocol/loan/asset_pool";
import { MsgSetTxProcess } from "./types/cfprotocol/loan/tx";
import { QueryGetObserveVoteRequest } from "./types/cfprotocol/loan/query";
import { QueryAllLoanEntityRequest } from "./types/cfprotocol/loan/query";
import { QueryAllLoanEntityResponse } from "./types/cfprotocol/loan/query";
import { QueryGetAccountBorrowedAssetsResponse } from "./types/cfprotocol/loan/query";
import { LoanObservationResponse } from "./types/cfprotocol/loan/query";
import { QueryAllLoanObservationRequest } from "./types/cfprotocol/loan/query";
import { LoanObservationAllResponse } from "./types/cfprotocol/loan/query";
import { ObserveVote } from "./types/cfprotocol/loan/observe_vote";
import { MsgRequestLoan } from "./types/cfprotocol/loan/tx";
import { QueryGetAccountSuppliedAssetsResponse } from "./types/cfprotocol/loan/query";
import { AccountSummary } from "./types/cfprotocol/loan/account_summary";
import { LoanTransactionResponse } from "./types/cfprotocol/loan/query";
import { QueryGetPoolSummaryRequest } from "./types/cfprotocol/loan/query";
import { QueryGetAvailableTransactionResponse } from "./types/cfprotocol/loan/query";
import { MsgObservationVote } from "./types/cfprotocol/loan/tx";
import { MsgUpdateParams } from "./types/cfprotocol/loan/tx";
import { LoanDetail } from "./types/cfprotocol/loan/loan_entity";
import { QueryGetAccountSuppliedAssetsRequest } from "./types/cfprotocol/loan/query";
import { GenesisState } from "./types/cfprotocol/loan/genesis";
import { MsgSetTxProcessResponse } from "./types/cfprotocol/loan/tx";
import { QueryParamsResponse } from "./types/cfprotocol/loan/query";


export { MsgRequestLoanResponse, QueryAllObserveVoteRequest, ObserveVoteAllResponse, ObserveVoteResponse, QueryGetLoanEntityResponse, QueryGetAccountSummaryResponse, PoolSummary, MsgUpdateParamsResponse, AssetBorrowed, QueryAllLoanTransactionRequest, QueryGetPoolListRequest, QueryGetLoanObservationRequest, MsgObservationVoteResponse, AssetSupplied, QueryGetLoanTransactionRequest, QueryGetAvailableTransactionRequest, LoanObservation, MsgVoteLoanTransaction, QueryParamsRequest, LoanTransactionAllResponse, QueryGetAccountBorrowedAssetsRequest, QueryGetPoolListResponse, Params, MsgVoteLoanTransactionResponse, QueryGetLoanEntityRequest, QueryGetAccountSummaryRequest, LoanTransaction, LoanEntity, QueryGetPoolSummaryResponse, AssetPool, MsgSetTxProcess, QueryGetObserveVoteRequest, QueryAllLoanEntityRequest, QueryAllLoanEntityResponse, QueryGetAccountBorrowedAssetsResponse, LoanObservationResponse, QueryAllLoanObservationRequest, LoanObservationAllResponse, ObserveVote, MsgRequestLoan, QueryGetAccountSuppliedAssetsResponse, AccountSummary, LoanTransactionResponse, QueryGetPoolSummaryRequest, QueryGetAvailableTransactionResponse, MsgObservationVote, MsgUpdateParams, LoanDetail, QueryGetAccountSuppliedAssetsRequest, GenesisState, MsgSetTxProcessResponse, QueryParamsResponse };

type sendMsgRequestLoanResponseParams = {
  value: MsgRequestLoanResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllObserveVoteRequestParams = {
  value: QueryAllObserveVoteRequest,
  fee?: StdFee,
  memo?: string
};

type sendObserveVoteAllResponseParams = {
  value: ObserveVoteAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendObserveVoteResponseParams = {
  value: ObserveVoteResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetLoanEntityResponseParams = {
  value: QueryGetLoanEntityResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountSummaryResponseParams = {
  value: QueryGetAccountSummaryResponse,
  fee?: StdFee,
  memo?: string
};

type sendPoolSummaryParams = {
  value: PoolSummary,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendAssetBorrowedParams = {
  value: AssetBorrowed,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllLoanTransactionRequestParams = {
  value: QueryAllLoanTransactionRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolListRequestParams = {
  value: QueryGetPoolListRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetLoanObservationRequestParams = {
  value: QueryGetLoanObservationRequest,
  fee?: StdFee,
  memo?: string
};

type sendMsgObservationVoteResponseParams = {
  value: MsgObservationVoteResponse,
  fee?: StdFee,
  memo?: string
};

type sendAssetSuppliedParams = {
  value: AssetSupplied,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetLoanTransactionRequestParams = {
  value: QueryGetLoanTransactionRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAvailableTransactionRequestParams = {
  value: QueryGetAvailableTransactionRequest,
  fee?: StdFee,
  memo?: string
};

type sendLoanObservationParams = {
  value: LoanObservation,
  fee?: StdFee,
  memo?: string
};

type sendMsgVoteLoanTransactionParams = {
  value: MsgVoteLoanTransaction,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendLoanTransactionAllResponseParams = {
  value: LoanTransactionAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountBorrowedAssetsRequestParams = {
  value: QueryGetAccountBorrowedAssetsRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolListResponseParams = {
  value: QueryGetPoolListResponse,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendMsgVoteLoanTransactionResponseParams = {
  value: MsgVoteLoanTransactionResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetLoanEntityRequestParams = {
  value: QueryGetLoanEntityRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountSummaryRequestParams = {
  value: QueryGetAccountSummaryRequest,
  fee?: StdFee,
  memo?: string
};

type sendLoanTransactionParams = {
  value: LoanTransaction,
  fee?: StdFee,
  memo?: string
};

type sendLoanEntityParams = {
  value: LoanEntity,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolSummaryResponseParams = {
  value: QueryGetPoolSummaryResponse,
  fee?: StdFee,
  memo?: string
};

type sendAssetPoolParams = {
  value: AssetPool,
  fee?: StdFee,
  memo?: string
};

type sendMsgSetTxProcessParams = {
  value: MsgSetTxProcess,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetObserveVoteRequestParams = {
  value: QueryGetObserveVoteRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllLoanEntityRequestParams = {
  value: QueryAllLoanEntityRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllLoanEntityResponseParams = {
  value: QueryAllLoanEntityResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountBorrowedAssetsResponseParams = {
  value: QueryGetAccountBorrowedAssetsResponse,
  fee?: StdFee,
  memo?: string
};

type sendLoanObservationResponseParams = {
  value: LoanObservationResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryAllLoanObservationRequestParams = {
  value: QueryAllLoanObservationRequest,
  fee?: StdFee,
  memo?: string
};

type sendLoanObservationAllResponseParams = {
  value: LoanObservationAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendObserveVoteParams = {
  value: ObserveVote,
  fee?: StdFee,
  memo?: string
};

type sendMsgRequestLoanParams = {
  value: MsgRequestLoan,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountSuppliedAssetsResponseParams = {
  value: QueryGetAccountSuppliedAssetsResponse,
  fee?: StdFee,
  memo?: string
};

type sendAccountSummaryParams = {
  value: AccountSummary,
  fee?: StdFee,
  memo?: string
};

type sendLoanTransactionResponseParams = {
  value: LoanTransactionResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetPoolSummaryRequestParams = {
  value: QueryGetPoolSummaryRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAvailableTransactionResponseParams = {
  value: QueryGetAvailableTransactionResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgObservationVoteParams = {
  value: MsgObservationVote,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendLoanDetailParams = {
  value: LoanDetail,
  fee?: StdFee,
  memo?: string
};

type sendQueryGetAccountSuppliedAssetsRequestParams = {
  value: QueryGetAccountSuppliedAssetsRequest,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendMsgSetTxProcessResponseParams = {
  value: MsgSetTxProcessResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};


type msgRequestLoanResponseParams = {
  value: MsgRequestLoanResponse,
};

type queryAllObserveVoteRequestParams = {
  value: QueryAllObserveVoteRequest,
};

type observeVoteAllResponseParams = {
  value: ObserveVoteAllResponse,
};

type observeVoteResponseParams = {
  value: ObserveVoteResponse,
};

type queryGetLoanEntityResponseParams = {
  value: QueryGetLoanEntityResponse,
};

type queryGetAccountSummaryResponseParams = {
  value: QueryGetAccountSummaryResponse,
};

type poolSummaryParams = {
  value: PoolSummary,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type assetBorrowedParams = {
  value: AssetBorrowed,
};

type queryAllLoanTransactionRequestParams = {
  value: QueryAllLoanTransactionRequest,
};

type queryGetPoolListRequestParams = {
  value: QueryGetPoolListRequest,
};

type queryGetLoanObservationRequestParams = {
  value: QueryGetLoanObservationRequest,
};

type msgObservationVoteResponseParams = {
  value: MsgObservationVoteResponse,
};

type assetSuppliedParams = {
  value: AssetSupplied,
};

type queryGetLoanTransactionRequestParams = {
  value: QueryGetLoanTransactionRequest,
};

type queryGetAvailableTransactionRequestParams = {
  value: QueryGetAvailableTransactionRequest,
};

type loanObservationParams = {
  value: LoanObservation,
};

type msgVoteLoanTransactionParams = {
  value: MsgVoteLoanTransaction,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type loanTransactionAllResponseParams = {
  value: LoanTransactionAllResponse,
};

type queryGetAccountBorrowedAssetsRequestParams = {
  value: QueryGetAccountBorrowedAssetsRequest,
};

type queryGetPoolListResponseParams = {
  value: QueryGetPoolListResponse,
};

type paramsParams = {
  value: Params,
};

type msgVoteLoanTransactionResponseParams = {
  value: MsgVoteLoanTransactionResponse,
};

type queryGetLoanEntityRequestParams = {
  value: QueryGetLoanEntityRequest,
};

type queryGetAccountSummaryRequestParams = {
  value: QueryGetAccountSummaryRequest,
};

type loanTransactionParams = {
  value: LoanTransaction,
};

type loanEntityParams = {
  value: LoanEntity,
};

type queryGetPoolSummaryResponseParams = {
  value: QueryGetPoolSummaryResponse,
};

type assetPoolParams = {
  value: AssetPool,
};

type msgSetTxProcessParams = {
  value: MsgSetTxProcess,
};

type queryGetObserveVoteRequestParams = {
  value: QueryGetObserveVoteRequest,
};

type queryAllLoanEntityRequestParams = {
  value: QueryAllLoanEntityRequest,
};

type queryAllLoanEntityResponseParams = {
  value: QueryAllLoanEntityResponse,
};

type queryGetAccountBorrowedAssetsResponseParams = {
  value: QueryGetAccountBorrowedAssetsResponse,
};

type loanObservationResponseParams = {
  value: LoanObservationResponse,
};

type queryAllLoanObservationRequestParams = {
  value: QueryAllLoanObservationRequest,
};

type loanObservationAllResponseParams = {
  value: LoanObservationAllResponse,
};

type observeVoteParams = {
  value: ObserveVote,
};

type msgRequestLoanParams = {
  value: MsgRequestLoan,
};

type queryGetAccountSuppliedAssetsResponseParams = {
  value: QueryGetAccountSuppliedAssetsResponse,
};

type accountSummaryParams = {
  value: AccountSummary,
};

type loanTransactionResponseParams = {
  value: LoanTransactionResponse,
};

type queryGetPoolSummaryRequestParams = {
  value: QueryGetPoolSummaryRequest,
};

type queryGetAvailableTransactionResponseParams = {
  value: QueryGetAvailableTransactionResponse,
};

type msgObservationVoteParams = {
  value: MsgObservationVote,
};

type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type loanDetailParams = {
  value: LoanDetail,
};

type queryGetAccountSuppliedAssetsRequestParams = {
  value: QueryGetAccountSuppliedAssetsRequest,
};

type genesisStateParams = {
  value: GenesisState,
};

type msgSetTxProcessResponseParams = {
  value: MsgSetTxProcessResponse,
};

type queryParamsResponseParams = {
  value: QueryParamsResponse,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgRequestLoanResponse({ value, fee, memo }: sendMsgRequestLoanResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRequestLoanResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRequestLoanResponse({ value: MsgRequestLoanResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRequestLoanResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllObserveVoteRequest({ value, fee, memo }: sendQueryAllObserveVoteRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllObserveVoteRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllObserveVoteRequest({ value: QueryAllObserveVoteRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllObserveVoteRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendObserveVoteAllResponse({ value, fee, memo }: sendObserveVoteAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendObserveVoteAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.observeVoteAllResponse({ value: ObserveVoteAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendObserveVoteAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendObserveVoteResponse({ value, fee, memo }: sendObserveVoteResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendObserveVoteResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.observeVoteResponse({ value: ObserveVoteResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendObserveVoteResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetLoanEntityResponse({ value, fee, memo }: sendQueryGetLoanEntityResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetLoanEntityResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetLoanEntityResponse({ value: QueryGetLoanEntityResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetLoanEntityResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountSummaryResponse({ value, fee, memo }: sendQueryGetAccountSummaryResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountSummaryResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountSummaryResponse({ value: QueryGetAccountSummaryResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountSummaryResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendPoolSummary({ value, fee, memo }: sendPoolSummaryParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendPoolSummary: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.poolSummary({ value: PoolSummary.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendPoolSummary: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendAssetBorrowed({ value, fee, memo }: sendAssetBorrowedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendAssetBorrowed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.assetBorrowed({ value: AssetBorrowed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendAssetBorrowed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllLoanTransactionRequest({ value, fee, memo }: sendQueryAllLoanTransactionRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllLoanTransactionRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllLoanTransactionRequest({ value: QueryAllLoanTransactionRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllLoanTransactionRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolListRequest({ value, fee, memo }: sendQueryGetPoolListRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolListRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolListRequest({ value: QueryGetPoolListRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolListRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetLoanObservationRequest({ value, fee, memo }: sendQueryGetLoanObservationRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetLoanObservationRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetLoanObservationRequest({ value: QueryGetLoanObservationRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetLoanObservationRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgObservationVoteResponse({ value, fee, memo }: sendMsgObservationVoteResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgObservationVoteResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgObservationVoteResponse({ value: MsgObservationVoteResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgObservationVoteResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendAssetSupplied({ value, fee, memo }: sendAssetSuppliedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendAssetSupplied: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.assetSupplied({ value: AssetSupplied.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendAssetSupplied: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetLoanTransactionRequest({ value, fee, memo }: sendQueryGetLoanTransactionRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetLoanTransactionRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetLoanTransactionRequest({ value: QueryGetLoanTransactionRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetLoanTransactionRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAvailableTransactionRequest({ value, fee, memo }: sendQueryGetAvailableTransactionRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAvailableTransactionRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAvailableTransactionRequest({ value: QueryGetAvailableTransactionRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAvailableTransactionRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanObservation({ value, fee, memo }: sendLoanObservationParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanObservation: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanObservation({ value: LoanObservation.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanObservation: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgVoteLoanTransaction({ value, fee, memo }: sendMsgVoteLoanTransactionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgVoteLoanTransaction: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgVoteLoanTransaction({ value: MsgVoteLoanTransaction.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgVoteLoanTransaction: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanTransactionAllResponse({ value, fee, memo }: sendLoanTransactionAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanTransactionAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanTransactionAllResponse({ value: LoanTransactionAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanTransactionAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountBorrowedAssetsRequest({ value, fee, memo }: sendQueryGetAccountBorrowedAssetsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountBorrowedAssetsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountBorrowedAssetsRequest({ value: QueryGetAccountBorrowedAssetsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountBorrowedAssetsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolListResponse({ value, fee, memo }: sendQueryGetPoolListResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolListResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolListResponse({ value: QueryGetPoolListResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolListResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgVoteLoanTransactionResponse({ value, fee, memo }: sendMsgVoteLoanTransactionResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgVoteLoanTransactionResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgVoteLoanTransactionResponse({ value: MsgVoteLoanTransactionResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgVoteLoanTransactionResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetLoanEntityRequest({ value, fee, memo }: sendQueryGetLoanEntityRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetLoanEntityRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetLoanEntityRequest({ value: QueryGetLoanEntityRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetLoanEntityRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountSummaryRequest({ value, fee, memo }: sendQueryGetAccountSummaryRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountSummaryRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountSummaryRequest({ value: QueryGetAccountSummaryRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountSummaryRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanTransaction({ value, fee, memo }: sendLoanTransactionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanTransaction: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanTransaction({ value: LoanTransaction.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanTransaction: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanEntity({ value, fee, memo }: sendLoanEntityParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanEntity: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanEntity({ value: LoanEntity.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanEntity: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolSummaryResponse({ value, fee, memo }: sendQueryGetPoolSummaryResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolSummaryResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolSummaryResponse({ value: QueryGetPoolSummaryResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolSummaryResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendAssetPool({ value, fee, memo }: sendAssetPoolParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendAssetPool: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.assetPool({ value: AssetPool.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendAssetPool: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSetTxProcess({ value, fee, memo }: sendMsgSetTxProcessParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetTxProcess: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSetTxProcess({ value: MsgSetTxProcess.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetTxProcess: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetObserveVoteRequest({ value, fee, memo }: sendQueryGetObserveVoteRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetObserveVoteRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetObserveVoteRequest({ value: QueryGetObserveVoteRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetObserveVoteRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllLoanEntityRequest({ value, fee, memo }: sendQueryAllLoanEntityRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllLoanEntityRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllLoanEntityRequest({ value: QueryAllLoanEntityRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllLoanEntityRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllLoanEntityResponse({ value, fee, memo }: sendQueryAllLoanEntityResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllLoanEntityResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllLoanEntityResponse({ value: QueryAllLoanEntityResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllLoanEntityResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountBorrowedAssetsResponse({ value, fee, memo }: sendQueryGetAccountBorrowedAssetsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountBorrowedAssetsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountBorrowedAssetsResponse({ value: QueryGetAccountBorrowedAssetsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountBorrowedAssetsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanObservationResponse({ value, fee, memo }: sendLoanObservationResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanObservationResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanObservationResponse({ value: LoanObservationResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanObservationResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAllLoanObservationRequest({ value, fee, memo }: sendQueryAllLoanObservationRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAllLoanObservationRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAllLoanObservationRequest({ value: QueryAllLoanObservationRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAllLoanObservationRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanObservationAllResponse({ value, fee, memo }: sendLoanObservationAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanObservationAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanObservationAllResponse({ value: LoanObservationAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanObservationAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendObserveVote({ value, fee, memo }: sendObserveVoteParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendObserveVote: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.observeVote({ value: ObserveVote.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendObserveVote: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRequestLoan({ value, fee, memo }: sendMsgRequestLoanParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRequestLoan: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRequestLoan({ value: MsgRequestLoan.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRequestLoan: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountSuppliedAssetsResponse({ value, fee, memo }: sendQueryGetAccountSuppliedAssetsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountSuppliedAssetsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountSuppliedAssetsResponse({ value: QueryGetAccountSuppliedAssetsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountSuppliedAssetsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendAccountSummary({ value, fee, memo }: sendAccountSummaryParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendAccountSummary: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.accountSummary({ value: AccountSummary.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendAccountSummary: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanTransactionResponse({ value, fee, memo }: sendLoanTransactionResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanTransactionResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanTransactionResponse({ value: LoanTransactionResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanTransactionResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetPoolSummaryRequest({ value, fee, memo }: sendQueryGetPoolSummaryRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetPoolSummaryRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetPoolSummaryRequest({ value: QueryGetPoolSummaryRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetPoolSummaryRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAvailableTransactionResponse({ value, fee, memo }: sendQueryGetAvailableTransactionResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAvailableTransactionResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAvailableTransactionResponse({ value: QueryGetAvailableTransactionResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAvailableTransactionResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgObservationVote({ value, fee, memo }: sendMsgObservationVoteParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgObservationVote: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgObservationVote({ value: MsgObservationVote.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgObservationVote: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendLoanDetail({ value, fee, memo }: sendLoanDetailParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendLoanDetail: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.loanDetail({ value: LoanDetail.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendLoanDetail: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryGetAccountSuppliedAssetsRequest({ value, fee, memo }: sendQueryGetAccountSuppliedAssetsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryGetAccountSuppliedAssetsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryGetAccountSuppliedAssetsRequest({ value: QueryGetAccountSuppliedAssetsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryGetAccountSuppliedAssetsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSetTxProcessResponse({ value, fee, memo }: sendMsgSetTxProcessResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetTxProcessResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSetTxProcessResponse({ value: MsgSetTxProcessResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetTxProcessResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgRequestLoanResponse({ value }: msgRequestLoanResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgRequestLoanResponse", value: MsgRequestLoanResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRequestLoanResponse: Could not create message: ' + e.message)
			}
		},
		
		queryAllObserveVoteRequest({ value }: queryAllObserveVoteRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryAllObserveVoteRequest", value: QueryAllObserveVoteRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllObserveVoteRequest: Could not create message: ' + e.message)
			}
		},
		
		observeVoteAllResponse({ value }: observeVoteAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.ObserveVoteAllResponse", value: ObserveVoteAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:ObserveVoteAllResponse: Could not create message: ' + e.message)
			}
		},
		
		observeVoteResponse({ value }: observeVoteResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.ObserveVoteResponse", value: ObserveVoteResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:ObserveVoteResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetLoanEntityResponse({ value }: queryGetLoanEntityResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetLoanEntityResponse", value: QueryGetLoanEntityResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetLoanEntityResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountSummaryResponse({ value }: queryGetAccountSummaryResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountSummaryResponse", value: QueryGetAccountSummaryResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountSummaryResponse: Could not create message: ' + e.message)
			}
		},
		
		poolSummary({ value }: poolSummaryParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.PoolSummary", value: PoolSummary.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:PoolSummary: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		assetBorrowed({ value }: assetBorrowedParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.AssetBorrowed", value: AssetBorrowed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:AssetBorrowed: Could not create message: ' + e.message)
			}
		},
		
		queryAllLoanTransactionRequest({ value }: queryAllLoanTransactionRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryAllLoanTransactionRequest", value: QueryAllLoanTransactionRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllLoanTransactionRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolListRequest({ value }: queryGetPoolListRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetPoolListRequest", value: QueryGetPoolListRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolListRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetLoanObservationRequest({ value }: queryGetLoanObservationRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetLoanObservationRequest", value: QueryGetLoanObservationRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetLoanObservationRequest: Could not create message: ' + e.message)
			}
		},
		
		msgObservationVoteResponse({ value }: msgObservationVoteResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgObservationVoteResponse", value: MsgObservationVoteResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgObservationVoteResponse: Could not create message: ' + e.message)
			}
		},
		
		assetSupplied({ value }: assetSuppliedParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.AssetSupplied", value: AssetSupplied.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:AssetSupplied: Could not create message: ' + e.message)
			}
		},
		
		queryGetLoanTransactionRequest({ value }: queryGetLoanTransactionRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetLoanTransactionRequest", value: QueryGetLoanTransactionRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetLoanTransactionRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetAvailableTransactionRequest({ value }: queryGetAvailableTransactionRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAvailableTransactionRequest", value: QueryGetAvailableTransactionRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAvailableTransactionRequest: Could not create message: ' + e.message)
			}
		},
		
		loanObservation({ value }: loanObservationParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanObservation", value: LoanObservation.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanObservation: Could not create message: ' + e.message)
			}
		},
		
		msgVoteLoanTransaction({ value }: msgVoteLoanTransactionParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgVoteLoanTransaction", value: MsgVoteLoanTransaction.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgVoteLoanTransaction: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		loanTransactionAllResponse({ value }: loanTransactionAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanTransactionAllResponse", value: LoanTransactionAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanTransactionAllResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountBorrowedAssetsRequest({ value }: queryGetAccountBorrowedAssetsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountBorrowedAssetsRequest", value: QueryGetAccountBorrowedAssetsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountBorrowedAssetsRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolListResponse({ value }: queryGetPoolListResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetPoolListResponse", value: QueryGetPoolListResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolListResponse: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		msgVoteLoanTransactionResponse({ value }: msgVoteLoanTransactionResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgVoteLoanTransactionResponse", value: MsgVoteLoanTransactionResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgVoteLoanTransactionResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetLoanEntityRequest({ value }: queryGetLoanEntityRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetLoanEntityRequest", value: QueryGetLoanEntityRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetLoanEntityRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountSummaryRequest({ value }: queryGetAccountSummaryRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountSummaryRequest", value: QueryGetAccountSummaryRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountSummaryRequest: Could not create message: ' + e.message)
			}
		},
		
		loanTransaction({ value }: loanTransactionParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanTransaction", value: LoanTransaction.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanTransaction: Could not create message: ' + e.message)
			}
		},
		
		loanEntity({ value }: loanEntityParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanEntity", value: LoanEntity.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanEntity: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolSummaryResponse({ value }: queryGetPoolSummaryResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetPoolSummaryResponse", value: QueryGetPoolSummaryResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolSummaryResponse: Could not create message: ' + e.message)
			}
		},
		
		assetPool({ value }: assetPoolParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.AssetPool", value: AssetPool.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:AssetPool: Could not create message: ' + e.message)
			}
		},
		
		msgSetTxProcess({ value }: msgSetTxProcessParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgSetTxProcess", value: MsgSetTxProcess.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetTxProcess: Could not create message: ' + e.message)
			}
		},
		
		queryGetObserveVoteRequest({ value }: queryGetObserveVoteRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetObserveVoteRequest", value: QueryGetObserveVoteRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetObserveVoteRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAllLoanEntityRequest({ value }: queryAllLoanEntityRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryAllLoanEntityRequest", value: QueryAllLoanEntityRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllLoanEntityRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAllLoanEntityResponse({ value }: queryAllLoanEntityResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryAllLoanEntityResponse", value: QueryAllLoanEntityResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllLoanEntityResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountBorrowedAssetsResponse({ value }: queryGetAccountBorrowedAssetsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountBorrowedAssetsResponse", value: QueryGetAccountBorrowedAssetsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountBorrowedAssetsResponse: Could not create message: ' + e.message)
			}
		},
		
		loanObservationResponse({ value }: loanObservationResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanObservationResponse", value: LoanObservationResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanObservationResponse: Could not create message: ' + e.message)
			}
		},
		
		queryAllLoanObservationRequest({ value }: queryAllLoanObservationRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryAllLoanObservationRequest", value: QueryAllLoanObservationRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAllLoanObservationRequest: Could not create message: ' + e.message)
			}
		},
		
		loanObservationAllResponse({ value }: loanObservationAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanObservationAllResponse", value: LoanObservationAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanObservationAllResponse: Could not create message: ' + e.message)
			}
		},
		
		observeVote({ value }: observeVoteParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.ObserveVote", value: ObserveVote.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:ObserveVote: Could not create message: ' + e.message)
			}
		},
		
		msgRequestLoan({ value }: msgRequestLoanParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgRequestLoan", value: MsgRequestLoan.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRequestLoan: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountSuppliedAssetsResponse({ value }: queryGetAccountSuppliedAssetsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountSuppliedAssetsResponse", value: QueryGetAccountSuppliedAssetsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountSuppliedAssetsResponse: Could not create message: ' + e.message)
			}
		},
		
		accountSummary({ value }: accountSummaryParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.AccountSummary", value: AccountSummary.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:AccountSummary: Could not create message: ' + e.message)
			}
		},
		
		loanTransactionResponse({ value }: loanTransactionResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanTransactionResponse", value: LoanTransactionResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanTransactionResponse: Could not create message: ' + e.message)
			}
		},
		
		queryGetPoolSummaryRequest({ value }: queryGetPoolSummaryRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetPoolSummaryRequest", value: QueryGetPoolSummaryRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetPoolSummaryRequest: Could not create message: ' + e.message)
			}
		},
		
		queryGetAvailableTransactionResponse({ value }: queryGetAvailableTransactionResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAvailableTransactionResponse", value: QueryGetAvailableTransactionResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAvailableTransactionResponse: Could not create message: ' + e.message)
			}
		},
		
		msgObservationVote({ value }: msgObservationVoteParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgObservationVote", value: MsgObservationVote.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgObservationVote: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		loanDetail({ value }: loanDetailParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.LoanDetail", value: LoanDetail.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:LoanDetail: Could not create message: ' + e.message)
			}
		},
		
		queryGetAccountSuppliedAssetsRequest({ value }: queryGetAccountSuppliedAssetsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryGetAccountSuppliedAssetsRequest", value: QueryGetAccountSuppliedAssetsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryGetAccountSuppliedAssetsRequest: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		msgSetTxProcessResponse({ value }: msgSetTxProcessResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.MsgSetTxProcessResponse", value: MsgSetTxProcessResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetTxProcessResponse: Could not create message: ' + e.message)
			}
		},
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.loan.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
	}
};

// interface QueryClientOptions {
//   addr: string
// }

// export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
//   return new Api({ baseURL: addr });
// };

class SDKModule {
	// public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		// this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			CfprotocolLoan: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;