// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/loan_entity.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.loan";

/** Loan defines loan details */
export interface LoanDetail {
  loanTxId: number;
  collateralId: number;
  collateralSymbol: string;
  collateralAmount: string;
  loanDuration: number;
  interestRate: string;
  loanRate: string;
  oraclePrice: string;
  loanAmount: string;
  status: string;
  loanAddress: string;
  health: string;
  reserved: string;
}

/** LoanEntity defines loan entities */
export interface LoanEntity {
  id: number;
  creator: string;
  loans: LoanDetail[];
}

function createBaseLoanDetail(): LoanDetail {
  return {
    loanTxId: 0,
    collateralId: 0,
    collateralSymbol: "",
    collateralAmount: "",
    loanDuration: 0,
    interestRate: "",
    loanRate: "",
    oraclePrice: "",
    loanAmount: "",
    status: "",
    loanAddress: "",
    health: "",
    reserved: "",
  };
}

export const LoanDetail: MessageFns<LoanDetail> = {
  encode(message: LoanDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loanTxId !== 0) {
      writer.uint32(8).uint64(message.loanTxId);
    }
    if (message.collateralId !== 0) {
      writer.uint32(16).uint64(message.collateralId);
    }
    if (message.collateralSymbol !== "") {
      writer.uint32(26).string(message.collateralSymbol);
    }
    if (message.collateralAmount !== "") {
      writer.uint32(34).string(message.collateralAmount);
    }
    if (message.loanDuration !== 0) {
      writer.uint32(40).uint64(message.loanDuration);
    }
    if (message.interestRate !== "") {
      writer.uint32(50).string(message.interestRate);
    }
    if (message.loanRate !== "") {
      writer.uint32(58).string(message.loanRate);
    }
    if (message.oraclePrice !== "") {
      writer.uint32(66).string(message.oraclePrice);
    }
    if (message.loanAmount !== "") {
      writer.uint32(74).string(message.loanAmount);
    }
    if (message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    if (message.loanAddress !== "") {
      writer.uint32(90).string(message.loanAddress);
    }
    if (message.health !== "") {
      writer.uint32(98).string(message.health);
    }
    if (message.reserved !== "") {
      writer.uint32(106).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.loanTxId = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.collateralId = longToNumber(reader.uint64());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.collateralSymbol = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.collateralAmount = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.loanDuration = longToNumber(reader.uint64());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.interestRate = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.loanRate = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.oraclePrice = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.loanAmount = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.loanAddress = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.health = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanDetail {
    return {
      loanTxId: isSet(object.loanTxId) ? globalThis.Number(object.loanTxId) : 0,
      collateralId: isSet(object.collateralId) ? globalThis.Number(object.collateralId) : 0,
      collateralSymbol: isSet(object.collateralSymbol) ? globalThis.String(object.collateralSymbol) : "",
      collateralAmount: isSet(object.collateralAmount) ? globalThis.String(object.collateralAmount) : "",
      loanDuration: isSet(object.loanDuration) ? globalThis.Number(object.loanDuration) : 0,
      interestRate: isSet(object.interestRate) ? globalThis.String(object.interestRate) : "",
      loanRate: isSet(object.loanRate) ? globalThis.String(object.loanRate) : "",
      oraclePrice: isSet(object.oraclePrice) ? globalThis.String(object.oraclePrice) : "",
      loanAmount: isSet(object.loanAmount) ? globalThis.String(object.loanAmount) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      loanAddress: isSet(object.loanAddress) ? globalThis.String(object.loanAddress) : "",
      health: isSet(object.health) ? globalThis.String(object.health) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: LoanDetail): unknown {
    const obj: any = {};
    if (message.loanTxId !== 0) {
      obj.loanTxId = Math.round(message.loanTxId);
    }
    if (message.collateralId !== 0) {
      obj.collateralId = Math.round(message.collateralId);
    }
    if (message.collateralSymbol !== "") {
      obj.collateralSymbol = message.collateralSymbol;
    }
    if (message.collateralAmount !== "") {
      obj.collateralAmount = message.collateralAmount;
    }
    if (message.loanDuration !== 0) {
      obj.loanDuration = Math.round(message.loanDuration);
    }
    if (message.interestRate !== "") {
      obj.interestRate = message.interestRate;
    }
    if (message.loanRate !== "") {
      obj.loanRate = message.loanRate;
    }
    if (message.oraclePrice !== "") {
      obj.oraclePrice = message.oraclePrice;
    }
    if (message.loanAmount !== "") {
      obj.loanAmount = message.loanAmount;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.loanAddress !== "") {
      obj.loanAddress = message.loanAddress;
    }
    if (message.health !== "") {
      obj.health = message.health;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanDetail>, I>>(base?: I): LoanDetail {
    return LoanDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanDetail>, I>>(object: I): LoanDetail {
    const message = createBaseLoanDetail();
    message.loanTxId = object.loanTxId ?? 0;
    message.collateralId = object.collateralId ?? 0;
    message.collateralSymbol = object.collateralSymbol ?? "";
    message.collateralAmount = object.collateralAmount ?? "";
    message.loanDuration = object.loanDuration ?? 0;
    message.interestRate = object.interestRate ?? "";
    message.loanRate = object.loanRate ?? "";
    message.oraclePrice = object.oraclePrice ?? "";
    message.loanAmount = object.loanAmount ?? "";
    message.status = object.status ?? "";
    message.loanAddress = object.loanAddress ?? "";
    message.health = object.health ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

function createBaseLoanEntity(): LoanEntity {
  return { id: 0, creator: "", loans: [] };
}

export const LoanEntity: MessageFns<LoanEntity> = {
  encode(message: LoanEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    for (const v of message.loans) {
      LoanDetail.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.loans.push(LoanDetail.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanEntity {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      loans: globalThis.Array.isArray(object?.loans) ? object.loans.map((e: any) => LoanDetail.fromJSON(e)) : [],
    };
  },

  toJSON(message: LoanEntity): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.loans?.length) {
      obj.loans = message.loans.map((e) => LoanDetail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanEntity>, I>>(base?: I): LoanEntity {
    return LoanEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanEntity>, I>>(object: I): LoanEntity {
    const message = createBaseLoanEntity();
    message.id = object.id ?? 0;
    message.creator = object.creator ?? "";
    message.loans = object.loans?.map((e) => LoanDetail.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
