// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/params.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.loan";

/** Params defines the parameters for the module. */
export interface Params {
  minInterestRate: string;
  maxLoanRate: string;
  minLiquidation: string;
  maxDuration: number;
  epochLength: number;
}

function createBaseParams(): Params {
  return { minInterestRate: "", maxLoanRate: "", minLiquidation: "", maxDuration: 0, epochLength: 0 };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minInterestRate !== "") {
      writer.uint32(10).string(message.minInterestRate);
    }
    if (message.maxLoanRate !== "") {
      writer.uint32(18).string(message.maxLoanRate);
    }
    if (message.minLiquidation !== "") {
      writer.uint32(26).string(message.minLiquidation);
    }
    if (message.maxDuration !== 0) {
      writer.uint32(32).uint64(message.maxDuration);
    }
    if (message.epochLength !== 0) {
      writer.uint32(40).uint64(message.epochLength);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.minInterestRate = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.maxLoanRate = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.minLiquidation = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.maxDuration = longToNumber(reader.uint64());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.epochLength = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      minInterestRate: isSet(object.minInterestRate) ? globalThis.String(object.minInterestRate) : "",
      maxLoanRate: isSet(object.maxLoanRate) ? globalThis.String(object.maxLoanRate) : "",
      minLiquidation: isSet(object.minLiquidation) ? globalThis.String(object.minLiquidation) : "",
      maxDuration: isSet(object.maxDuration) ? globalThis.Number(object.maxDuration) : 0,
      epochLength: isSet(object.epochLength) ? globalThis.Number(object.epochLength) : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.minInterestRate !== "") {
      obj.minInterestRate = message.minInterestRate;
    }
    if (message.maxLoanRate !== "") {
      obj.maxLoanRate = message.maxLoanRate;
    }
    if (message.minLiquidation !== "") {
      obj.minLiquidation = message.minLiquidation;
    }
    if (message.maxDuration !== 0) {
      obj.maxDuration = Math.round(message.maxDuration);
    }
    if (message.epochLength !== 0) {
      obj.epochLength = Math.round(message.epochLength);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.minInterestRate = object.minInterestRate ?? "";
    message.maxLoanRate = object.maxLoanRate ?? "";
    message.minLiquidation = object.minLiquidation ?? "";
    message.maxDuration = object.maxDuration ?? 0;
    message.epochLength = object.epochLength ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
