// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../cosmos/base/query/v1beta1/pagination";
import { AccountSummary } from "./account_summary";
import { AssetBorrowed } from "./asset_borrowed";
import { AssetPool } from "./asset_pool";
import { AssetSupplied } from "./asset_supplied";
import { LoanEntity } from "./loan_entity";
import { LoanObservation } from "./loan_observation";
import { ObserveVote } from "./observe_vote";
import { Params } from "./params";
import { PoolSummary } from "./pool_summary";
import { LoanTransaction } from "./transaction";

export const protobufPackage = "cfprotocol.loan";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetLoanTransactionRequest is request type for the Query/GetLoanTransactionRequest RPC method. */
export interface QueryGetLoanTransactionRequest {
  id: number;
}

/** LoanTransactionResponse is response type for the Query/GetLoanTransactionRequest RPC method. */
export interface LoanTransactionResponse {
  loanTransaction: LoanTransaction | undefined;
}

/** QueryAllLoanTransactionRequest is request type for the Query/AllLoanTransactionRequest RPC method. */
export interface QueryAllLoanTransactionRequest {
  pagination: PageRequest | undefined;
}

/** LoanTransactionAllResponse is response type for the Query/AllLoanTransactionRequest RPC method. */
export interface LoanTransactionAllResponse {
  loanTransaction: LoanTransaction[];
  pagination: PageResponse | undefined;
}

/** QueryGetLoanObservationRequest is request type for the Query/GetLoanObservationRequest RPC method. */
export interface QueryGetLoanObservationRequest {
  id: number;
}

/** LoanObservationResponse is response type for the Query/QueryGetLoanObservationRequest RPC method. */
export interface LoanObservationResponse {
  loanObservation: LoanObservation | undefined;
}

/** QueryAllLoanObservationRequest is request type for the Query/AllLoanObservationRequest RPC method. */
export interface QueryAllLoanObservationRequest {
  pagination: PageRequest | undefined;
}

/** LoanObservationAllResponse is response type for the Query/AllLoanObservationRequest RPC method. */
export interface LoanObservationAllResponse {
  loanObservation: LoanObservation[];
  pagination: PageResponse | undefined;
}

/** QueryGetAvailableTransactionRequest is request type for the Query/GetAvailableTransactionRequest RPC method. */
export interface QueryGetAvailableTransactionRequest {
}

/** QueryGetAvailableTransactionResponse is response type for the Query/GetAvailableTransactionRequest RPC method. */
export interface QueryGetAvailableTransactionResponse {
  transactionData: LoanTransaction[];
}

/** QueryGetObserveVoteRequest is request type for the Query/GetObserveVoteRequest RPC method. */
export interface QueryGetObserveVoteRequest {
  id: number;
}

/** ObserveVoteResponse is response type for the Query/QueryGetObserveVoteRequest RPC method. */
export interface ObserveVoteResponse {
  observeVote: ObserveVote | undefined;
}

/** QueryAllObserveVoteRequest is request type for the Query/AllObserveVoteRequest RPC method. */
export interface QueryAllObserveVoteRequest {
  pagination: PageRequest | undefined;
}

/** ObserveVoteAllResponse is response type for the Query/AllObserveVoteResponse RPC method. */
export interface ObserveVoteAllResponse {
  observeVote: ObserveVote[];
  pagination: PageResponse | undefined;
}

export interface QueryGetLoanEntityRequest {
  id: number;
}

export interface QueryGetLoanEntityResponse {
  LoanEntity: LoanEntity | undefined;
}

export interface QueryAllLoanEntityRequest {
  pagination: PageRequest | undefined;
}

export interface QueryAllLoanEntityResponse {
  loanEntity: LoanEntity[];
  pagination: PageResponse | undefined;
}

export interface QueryGetAccountSummaryRequest {
  user: string;
}

export interface QueryGetAccountSummaryResponse {
  accountSummary: AccountSummary | undefined;
}

export interface QueryGetAccountSuppliedAssetsRequest {
  user: string;
}

export interface QueryGetAccountSuppliedAssetsResponse {
  assetSupplied: AssetSupplied[];
}

export interface QueryGetAccountBorrowedAssetsRequest {
  user: string;
}

export interface QueryGetAccountBorrowedAssetsResponse {
  assetBorrowed: AssetBorrowed[];
}

export interface QueryGetPoolSummaryRequest {
}

export interface QueryGetPoolSummaryResponse {
  poolSummary: PoolSummary | undefined;
}

export interface QueryGetPoolListRequest {
}

export interface QueryGetPoolListResponse {
  assetPool: AssetPool[];
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetLoanTransactionRequest(): QueryGetLoanTransactionRequest {
  return { id: 0 };
}

export const QueryGetLoanTransactionRequest: MessageFns<QueryGetLoanTransactionRequest> = {
  encode(message: QueryGetLoanTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetLoanTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetLoanTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetLoanTransactionRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetLoanTransactionRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetLoanTransactionRequest>, I>>(base?: I): QueryGetLoanTransactionRequest {
    return QueryGetLoanTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetLoanTransactionRequest>, I>>(
    object: I,
  ): QueryGetLoanTransactionRequest {
    const message = createBaseQueryGetLoanTransactionRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseLoanTransactionResponse(): LoanTransactionResponse {
  return { loanTransaction: undefined };
}

export const LoanTransactionResponse: MessageFns<LoanTransactionResponse> = {
  encode(message: LoanTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loanTransaction !== undefined) {
      LoanTransaction.encode(message.loanTransaction, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.loanTransaction = LoanTransaction.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanTransactionResponse {
    return {
      loanTransaction: isSet(object.loanTransaction) ? LoanTransaction.fromJSON(object.loanTransaction) : undefined,
    };
  },

  toJSON(message: LoanTransactionResponse): unknown {
    const obj: any = {};
    if (message.loanTransaction !== undefined) {
      obj.loanTransaction = LoanTransaction.toJSON(message.loanTransaction);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanTransactionResponse>, I>>(base?: I): LoanTransactionResponse {
    return LoanTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanTransactionResponse>, I>>(object: I): LoanTransactionResponse {
    const message = createBaseLoanTransactionResponse();
    message.loanTransaction = (object.loanTransaction !== undefined && object.loanTransaction !== null)
      ? LoanTransaction.fromPartial(object.loanTransaction)
      : undefined;
    return message;
  },
};

function createBaseQueryAllLoanTransactionRequest(): QueryAllLoanTransactionRequest {
  return { pagination: undefined };
}

export const QueryAllLoanTransactionRequest: MessageFns<QueryAllLoanTransactionRequest> = {
  encode(message: QueryAllLoanTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllLoanTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllLoanTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllLoanTransactionRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllLoanTransactionRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllLoanTransactionRequest>, I>>(base?: I): QueryAllLoanTransactionRequest {
    return QueryAllLoanTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllLoanTransactionRequest>, I>>(
    object: I,
  ): QueryAllLoanTransactionRequest {
    const message = createBaseQueryAllLoanTransactionRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseLoanTransactionAllResponse(): LoanTransactionAllResponse {
  return { loanTransaction: [], pagination: undefined };
}

export const LoanTransactionAllResponse: MessageFns<LoanTransactionAllResponse> = {
  encode(message: LoanTransactionAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.loanTransaction) {
      LoanTransaction.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanTransactionAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanTransactionAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.loanTransaction.push(LoanTransaction.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanTransactionAllResponse {
    return {
      loanTransaction: globalThis.Array.isArray(object?.loanTransaction)
        ? object.loanTransaction.map((e: any) => LoanTransaction.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: LoanTransactionAllResponse): unknown {
    const obj: any = {};
    if (message.loanTransaction?.length) {
      obj.loanTransaction = message.loanTransaction.map((e) => LoanTransaction.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanTransactionAllResponse>, I>>(base?: I): LoanTransactionAllResponse {
    return LoanTransactionAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanTransactionAllResponse>, I>>(object: I): LoanTransactionAllResponse {
    const message = createBaseLoanTransactionAllResponse();
    message.loanTransaction = object.loanTransaction?.map((e) => LoanTransaction.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetLoanObservationRequest(): QueryGetLoanObservationRequest {
  return { id: 0 };
}

export const QueryGetLoanObservationRequest: MessageFns<QueryGetLoanObservationRequest> = {
  encode(message: QueryGetLoanObservationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetLoanObservationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetLoanObservationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetLoanObservationRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetLoanObservationRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetLoanObservationRequest>, I>>(base?: I): QueryGetLoanObservationRequest {
    return QueryGetLoanObservationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetLoanObservationRequest>, I>>(
    object: I,
  ): QueryGetLoanObservationRequest {
    const message = createBaseQueryGetLoanObservationRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseLoanObservationResponse(): LoanObservationResponse {
  return { loanObservation: undefined };
}

export const LoanObservationResponse: MessageFns<LoanObservationResponse> = {
  encode(message: LoanObservationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loanObservation !== undefined) {
      LoanObservation.encode(message.loanObservation, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanObservationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanObservationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.loanObservation = LoanObservation.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanObservationResponse {
    return {
      loanObservation: isSet(object.loanObservation) ? LoanObservation.fromJSON(object.loanObservation) : undefined,
    };
  },

  toJSON(message: LoanObservationResponse): unknown {
    const obj: any = {};
    if (message.loanObservation !== undefined) {
      obj.loanObservation = LoanObservation.toJSON(message.loanObservation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanObservationResponse>, I>>(base?: I): LoanObservationResponse {
    return LoanObservationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanObservationResponse>, I>>(object: I): LoanObservationResponse {
    const message = createBaseLoanObservationResponse();
    message.loanObservation = (object.loanObservation !== undefined && object.loanObservation !== null)
      ? LoanObservation.fromPartial(object.loanObservation)
      : undefined;
    return message;
  },
};

function createBaseQueryAllLoanObservationRequest(): QueryAllLoanObservationRequest {
  return { pagination: undefined };
}

export const QueryAllLoanObservationRequest: MessageFns<QueryAllLoanObservationRequest> = {
  encode(message: QueryAllLoanObservationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllLoanObservationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllLoanObservationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllLoanObservationRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllLoanObservationRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllLoanObservationRequest>, I>>(base?: I): QueryAllLoanObservationRequest {
    return QueryAllLoanObservationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllLoanObservationRequest>, I>>(
    object: I,
  ): QueryAllLoanObservationRequest {
    const message = createBaseQueryAllLoanObservationRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseLoanObservationAllResponse(): LoanObservationAllResponse {
  return { loanObservation: [], pagination: undefined };
}

export const LoanObservationAllResponse: MessageFns<LoanObservationAllResponse> = {
  encode(message: LoanObservationAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.loanObservation) {
      LoanObservation.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanObservationAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanObservationAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.loanObservation.push(LoanObservation.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanObservationAllResponse {
    return {
      loanObservation: globalThis.Array.isArray(object?.loanObservation)
        ? object.loanObservation.map((e: any) => LoanObservation.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: LoanObservationAllResponse): unknown {
    const obj: any = {};
    if (message.loanObservation?.length) {
      obj.loanObservation = message.loanObservation.map((e) => LoanObservation.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanObservationAllResponse>, I>>(base?: I): LoanObservationAllResponse {
    return LoanObservationAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanObservationAllResponse>, I>>(object: I): LoanObservationAllResponse {
    const message = createBaseLoanObservationAllResponse();
    message.loanObservation = object.loanObservation?.map((e) => LoanObservation.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetAvailableTransactionRequest(): QueryGetAvailableTransactionRequest {
  return {};
}

export const QueryGetAvailableTransactionRequest: MessageFns<QueryGetAvailableTransactionRequest> = {
  encode(_: QueryGetAvailableTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAvailableTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAvailableTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryGetAvailableTransactionRequest {
    return {};
  },

  toJSON(_: QueryGetAvailableTransactionRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAvailableTransactionRequest>, I>>(
    base?: I,
  ): QueryGetAvailableTransactionRequest {
    return QueryGetAvailableTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAvailableTransactionRequest>, I>>(
    _: I,
  ): QueryGetAvailableTransactionRequest {
    const message = createBaseQueryGetAvailableTransactionRequest();
    return message;
  },
};

function createBaseQueryGetAvailableTransactionResponse(): QueryGetAvailableTransactionResponse {
  return { transactionData: [] };
}

export const QueryGetAvailableTransactionResponse: MessageFns<QueryGetAvailableTransactionResponse> = {
  encode(message: QueryGetAvailableTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transactionData) {
      LoanTransaction.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAvailableTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAvailableTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.transactionData.push(LoanTransaction.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAvailableTransactionResponse {
    return {
      transactionData: globalThis.Array.isArray(object?.transactionData)
        ? object.transactionData.map((e: any) => LoanTransaction.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryGetAvailableTransactionResponse): unknown {
    const obj: any = {};
    if (message.transactionData?.length) {
      obj.transactionData = message.transactionData.map((e) => LoanTransaction.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAvailableTransactionResponse>, I>>(
    base?: I,
  ): QueryGetAvailableTransactionResponse {
    return QueryGetAvailableTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAvailableTransactionResponse>, I>>(
    object: I,
  ): QueryGetAvailableTransactionResponse {
    const message = createBaseQueryGetAvailableTransactionResponse();
    message.transactionData = object.transactionData?.map((e) => LoanTransaction.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryGetObserveVoteRequest(): QueryGetObserveVoteRequest {
  return { id: 0 };
}

export const QueryGetObserveVoteRequest: MessageFns<QueryGetObserveVoteRequest> = {
  encode(message: QueryGetObserveVoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetObserveVoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetObserveVoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetObserveVoteRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetObserveVoteRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetObserveVoteRequest>, I>>(base?: I): QueryGetObserveVoteRequest {
    return QueryGetObserveVoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetObserveVoteRequest>, I>>(object: I): QueryGetObserveVoteRequest {
    const message = createBaseQueryGetObserveVoteRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseObserveVoteResponse(): ObserveVoteResponse {
  return { observeVote: undefined };
}

export const ObserveVoteResponse: MessageFns<ObserveVoteResponse> = {
  encode(message: ObserveVoteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.observeVote !== undefined) {
      ObserveVote.encode(message.observeVote, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObserveVoteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObserveVoteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.observeVote = ObserveVote.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObserveVoteResponse {
    return { observeVote: isSet(object.observeVote) ? ObserveVote.fromJSON(object.observeVote) : undefined };
  },

  toJSON(message: ObserveVoteResponse): unknown {
    const obj: any = {};
    if (message.observeVote !== undefined) {
      obj.observeVote = ObserveVote.toJSON(message.observeVote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObserveVoteResponse>, I>>(base?: I): ObserveVoteResponse {
    return ObserveVoteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObserveVoteResponse>, I>>(object: I): ObserveVoteResponse {
    const message = createBaseObserveVoteResponse();
    message.observeVote = (object.observeVote !== undefined && object.observeVote !== null)
      ? ObserveVote.fromPartial(object.observeVote)
      : undefined;
    return message;
  },
};

function createBaseQueryAllObserveVoteRequest(): QueryAllObserveVoteRequest {
  return { pagination: undefined };
}

export const QueryAllObserveVoteRequest: MessageFns<QueryAllObserveVoteRequest> = {
  encode(message: QueryAllObserveVoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllObserveVoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllObserveVoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllObserveVoteRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllObserveVoteRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllObserveVoteRequest>, I>>(base?: I): QueryAllObserveVoteRequest {
    return QueryAllObserveVoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllObserveVoteRequest>, I>>(object: I): QueryAllObserveVoteRequest {
    const message = createBaseQueryAllObserveVoteRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseObserveVoteAllResponse(): ObserveVoteAllResponse {
  return { observeVote: [], pagination: undefined };
}

export const ObserveVoteAllResponse: MessageFns<ObserveVoteAllResponse> = {
  encode(message: ObserveVoteAllResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.observeVote) {
      ObserveVote.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObserveVoteAllResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObserveVoteAllResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.observeVote.push(ObserveVote.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObserveVoteAllResponse {
    return {
      observeVote: globalThis.Array.isArray(object?.observeVote)
        ? object.observeVote.map((e: any) => ObserveVote.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: ObserveVoteAllResponse): unknown {
    const obj: any = {};
    if (message.observeVote?.length) {
      obj.observeVote = message.observeVote.map((e) => ObserveVote.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObserveVoteAllResponse>, I>>(base?: I): ObserveVoteAllResponse {
    return ObserveVoteAllResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObserveVoteAllResponse>, I>>(object: I): ObserveVoteAllResponse {
    const message = createBaseObserveVoteAllResponse();
    message.observeVote = object.observeVote?.map((e) => ObserveVote.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetLoanEntityRequest(): QueryGetLoanEntityRequest {
  return { id: 0 };
}

export const QueryGetLoanEntityRequest: MessageFns<QueryGetLoanEntityRequest> = {
  encode(message: QueryGetLoanEntityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetLoanEntityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetLoanEntityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetLoanEntityRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetLoanEntityRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetLoanEntityRequest>, I>>(base?: I): QueryGetLoanEntityRequest {
    return QueryGetLoanEntityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetLoanEntityRequest>, I>>(object: I): QueryGetLoanEntityRequest {
    const message = createBaseQueryGetLoanEntityRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetLoanEntityResponse(): QueryGetLoanEntityResponse {
  return { LoanEntity: undefined };
}

export const QueryGetLoanEntityResponse: MessageFns<QueryGetLoanEntityResponse> = {
  encode(message: QueryGetLoanEntityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.LoanEntity !== undefined) {
      LoanEntity.encode(message.LoanEntity, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetLoanEntityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetLoanEntityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.LoanEntity = LoanEntity.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetLoanEntityResponse {
    return { LoanEntity: isSet(object.LoanEntity) ? LoanEntity.fromJSON(object.LoanEntity) : undefined };
  },

  toJSON(message: QueryGetLoanEntityResponse): unknown {
    const obj: any = {};
    if (message.LoanEntity !== undefined) {
      obj.LoanEntity = LoanEntity.toJSON(message.LoanEntity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetLoanEntityResponse>, I>>(base?: I): QueryGetLoanEntityResponse {
    return QueryGetLoanEntityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetLoanEntityResponse>, I>>(object: I): QueryGetLoanEntityResponse {
    const message = createBaseQueryGetLoanEntityResponse();
    message.LoanEntity = (object.LoanEntity !== undefined && object.LoanEntity !== null)
      ? LoanEntity.fromPartial(object.LoanEntity)
      : undefined;
    return message;
  },
};

function createBaseQueryAllLoanEntityRequest(): QueryAllLoanEntityRequest {
  return { pagination: undefined };
}

export const QueryAllLoanEntityRequest: MessageFns<QueryAllLoanEntityRequest> = {
  encode(message: QueryAllLoanEntityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllLoanEntityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllLoanEntityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllLoanEntityRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllLoanEntityRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllLoanEntityRequest>, I>>(base?: I): QueryAllLoanEntityRequest {
    return QueryAllLoanEntityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllLoanEntityRequest>, I>>(object: I): QueryAllLoanEntityRequest {
    const message = createBaseQueryAllLoanEntityRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllLoanEntityResponse(): QueryAllLoanEntityResponse {
  return { loanEntity: [], pagination: undefined };
}

export const QueryAllLoanEntityResponse: MessageFns<QueryAllLoanEntityResponse> = {
  encode(message: QueryAllLoanEntityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.loanEntity) {
      LoanEntity.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllLoanEntityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllLoanEntityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.loanEntity.push(LoanEntity.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllLoanEntityResponse {
    return {
      loanEntity: globalThis.Array.isArray(object?.loanEntity)
        ? object.loanEntity.map((e: any) => LoanEntity.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllLoanEntityResponse): unknown {
    const obj: any = {};
    if (message.loanEntity?.length) {
      obj.loanEntity = message.loanEntity.map((e) => LoanEntity.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllLoanEntityResponse>, I>>(base?: I): QueryAllLoanEntityResponse {
    return QueryAllLoanEntityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllLoanEntityResponse>, I>>(object: I): QueryAllLoanEntityResponse {
    const message = createBaseQueryAllLoanEntityResponse();
    message.loanEntity = object.loanEntity?.map((e) => LoanEntity.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetAccountSummaryRequest(): QueryGetAccountSummaryRequest {
  return { user: "" };
}

export const QueryGetAccountSummaryRequest: MessageFns<QueryGetAccountSummaryRequest> = {
  encode(message: QueryGetAccountSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountSummaryRequest {
    return { user: isSet(object.user) ? globalThis.String(object.user) : "" };
  },

  toJSON(message: QueryGetAccountSummaryRequest): unknown {
    const obj: any = {};
    if (message.user !== "") {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountSummaryRequest>, I>>(base?: I): QueryGetAccountSummaryRequest {
    return QueryGetAccountSummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountSummaryRequest>, I>>(
    object: I,
  ): QueryGetAccountSummaryRequest {
    const message = createBaseQueryGetAccountSummaryRequest();
    message.user = object.user ?? "";
    return message;
  },
};

function createBaseQueryGetAccountSummaryResponse(): QueryGetAccountSummaryResponse {
  return { accountSummary: undefined };
}

export const QueryGetAccountSummaryResponse: MessageFns<QueryGetAccountSummaryResponse> = {
  encode(message: QueryGetAccountSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountSummary !== undefined) {
      AccountSummary.encode(message.accountSummary, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.accountSummary = AccountSummary.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountSummaryResponse {
    return {
      accountSummary: isSet(object.accountSummary) ? AccountSummary.fromJSON(object.accountSummary) : undefined,
    };
  },

  toJSON(message: QueryGetAccountSummaryResponse): unknown {
    const obj: any = {};
    if (message.accountSummary !== undefined) {
      obj.accountSummary = AccountSummary.toJSON(message.accountSummary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountSummaryResponse>, I>>(base?: I): QueryGetAccountSummaryResponse {
    return QueryGetAccountSummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountSummaryResponse>, I>>(
    object: I,
  ): QueryGetAccountSummaryResponse {
    const message = createBaseQueryGetAccountSummaryResponse();
    message.accountSummary = (object.accountSummary !== undefined && object.accountSummary !== null)
      ? AccountSummary.fromPartial(object.accountSummary)
      : undefined;
    return message;
  },
};

function createBaseQueryGetAccountSuppliedAssetsRequest(): QueryGetAccountSuppliedAssetsRequest {
  return { user: "" };
}

export const QueryGetAccountSuppliedAssetsRequest: MessageFns<QueryGetAccountSuppliedAssetsRequest> = {
  encode(message: QueryGetAccountSuppliedAssetsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountSuppliedAssetsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountSuppliedAssetsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountSuppliedAssetsRequest {
    return { user: isSet(object.user) ? globalThis.String(object.user) : "" };
  },

  toJSON(message: QueryGetAccountSuppliedAssetsRequest): unknown {
    const obj: any = {};
    if (message.user !== "") {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountSuppliedAssetsRequest>, I>>(
    base?: I,
  ): QueryGetAccountSuppliedAssetsRequest {
    return QueryGetAccountSuppliedAssetsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountSuppliedAssetsRequest>, I>>(
    object: I,
  ): QueryGetAccountSuppliedAssetsRequest {
    const message = createBaseQueryGetAccountSuppliedAssetsRequest();
    message.user = object.user ?? "";
    return message;
  },
};

function createBaseQueryGetAccountSuppliedAssetsResponse(): QueryGetAccountSuppliedAssetsResponse {
  return { assetSupplied: [] };
}

export const QueryGetAccountSuppliedAssetsResponse: MessageFns<QueryGetAccountSuppliedAssetsResponse> = {
  encode(message: QueryGetAccountSuppliedAssetsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.assetSupplied) {
      AssetSupplied.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountSuppliedAssetsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountSuppliedAssetsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.assetSupplied.push(AssetSupplied.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountSuppliedAssetsResponse {
    return {
      assetSupplied: globalThis.Array.isArray(object?.assetSupplied)
        ? object.assetSupplied.map((e: any) => AssetSupplied.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryGetAccountSuppliedAssetsResponse): unknown {
    const obj: any = {};
    if (message.assetSupplied?.length) {
      obj.assetSupplied = message.assetSupplied.map((e) => AssetSupplied.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountSuppliedAssetsResponse>, I>>(
    base?: I,
  ): QueryGetAccountSuppliedAssetsResponse {
    return QueryGetAccountSuppliedAssetsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountSuppliedAssetsResponse>, I>>(
    object: I,
  ): QueryGetAccountSuppliedAssetsResponse {
    const message = createBaseQueryGetAccountSuppliedAssetsResponse();
    message.assetSupplied = object.assetSupplied?.map((e) => AssetSupplied.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryGetAccountBorrowedAssetsRequest(): QueryGetAccountBorrowedAssetsRequest {
  return { user: "" };
}

export const QueryGetAccountBorrowedAssetsRequest: MessageFns<QueryGetAccountBorrowedAssetsRequest> = {
  encode(message: QueryGetAccountBorrowedAssetsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountBorrowedAssetsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountBorrowedAssetsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountBorrowedAssetsRequest {
    return { user: isSet(object.user) ? globalThis.String(object.user) : "" };
  },

  toJSON(message: QueryGetAccountBorrowedAssetsRequest): unknown {
    const obj: any = {};
    if (message.user !== "") {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountBorrowedAssetsRequest>, I>>(
    base?: I,
  ): QueryGetAccountBorrowedAssetsRequest {
    return QueryGetAccountBorrowedAssetsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountBorrowedAssetsRequest>, I>>(
    object: I,
  ): QueryGetAccountBorrowedAssetsRequest {
    const message = createBaseQueryGetAccountBorrowedAssetsRequest();
    message.user = object.user ?? "";
    return message;
  },
};

function createBaseQueryGetAccountBorrowedAssetsResponse(): QueryGetAccountBorrowedAssetsResponse {
  return { assetBorrowed: [] };
}

export const QueryGetAccountBorrowedAssetsResponse: MessageFns<QueryGetAccountBorrowedAssetsResponse> = {
  encode(message: QueryGetAccountBorrowedAssetsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.assetBorrowed) {
      AssetBorrowed.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetAccountBorrowedAssetsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetAccountBorrowedAssetsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.assetBorrowed.push(AssetBorrowed.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetAccountBorrowedAssetsResponse {
    return {
      assetBorrowed: globalThis.Array.isArray(object?.assetBorrowed)
        ? object.assetBorrowed.map((e: any) => AssetBorrowed.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryGetAccountBorrowedAssetsResponse): unknown {
    const obj: any = {};
    if (message.assetBorrowed?.length) {
      obj.assetBorrowed = message.assetBorrowed.map((e) => AssetBorrowed.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetAccountBorrowedAssetsResponse>, I>>(
    base?: I,
  ): QueryGetAccountBorrowedAssetsResponse {
    return QueryGetAccountBorrowedAssetsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetAccountBorrowedAssetsResponse>, I>>(
    object: I,
  ): QueryGetAccountBorrowedAssetsResponse {
    const message = createBaseQueryGetAccountBorrowedAssetsResponse();
    message.assetBorrowed = object.assetBorrowed?.map((e) => AssetBorrowed.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryGetPoolSummaryRequest(): QueryGetPoolSummaryRequest {
  return {};
}

export const QueryGetPoolSummaryRequest: MessageFns<QueryGetPoolSummaryRequest> = {
  encode(_: QueryGetPoolSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPoolSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPoolSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryGetPoolSummaryRequest {
    return {};
  },

  toJSON(_: QueryGetPoolSummaryRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPoolSummaryRequest>, I>>(base?: I): QueryGetPoolSummaryRequest {
    return QueryGetPoolSummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPoolSummaryRequest>, I>>(_: I): QueryGetPoolSummaryRequest {
    const message = createBaseQueryGetPoolSummaryRequest();
    return message;
  },
};

function createBaseQueryGetPoolSummaryResponse(): QueryGetPoolSummaryResponse {
  return { poolSummary: undefined };
}

export const QueryGetPoolSummaryResponse: MessageFns<QueryGetPoolSummaryResponse> = {
  encode(message: QueryGetPoolSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolSummary !== undefined) {
      PoolSummary.encode(message.poolSummary, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPoolSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPoolSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.poolSummary = PoolSummary.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetPoolSummaryResponse {
    return { poolSummary: isSet(object.poolSummary) ? PoolSummary.fromJSON(object.poolSummary) : undefined };
  },

  toJSON(message: QueryGetPoolSummaryResponse): unknown {
    const obj: any = {};
    if (message.poolSummary !== undefined) {
      obj.poolSummary = PoolSummary.toJSON(message.poolSummary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPoolSummaryResponse>, I>>(base?: I): QueryGetPoolSummaryResponse {
    return QueryGetPoolSummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPoolSummaryResponse>, I>>(object: I): QueryGetPoolSummaryResponse {
    const message = createBaseQueryGetPoolSummaryResponse();
    message.poolSummary = (object.poolSummary !== undefined && object.poolSummary !== null)
      ? PoolSummary.fromPartial(object.poolSummary)
      : undefined;
    return message;
  },
};

function createBaseQueryGetPoolListRequest(): QueryGetPoolListRequest {
  return {};
}

export const QueryGetPoolListRequest: MessageFns<QueryGetPoolListRequest> = {
  encode(_: QueryGetPoolListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPoolListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPoolListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryGetPoolListRequest {
    return {};
  },

  toJSON(_: QueryGetPoolListRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPoolListRequest>, I>>(base?: I): QueryGetPoolListRequest {
    return QueryGetPoolListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPoolListRequest>, I>>(_: I): QueryGetPoolListRequest {
    const message = createBaseQueryGetPoolListRequest();
    return message;
  },
};

function createBaseQueryGetPoolListResponse(): QueryGetPoolListResponse {
  return { assetPool: [] };
}

export const QueryGetPoolListResponse: MessageFns<QueryGetPoolListResponse> = {
  encode(message: QueryGetPoolListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.assetPool) {
      AssetPool.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPoolListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPoolListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.assetPool.push(AssetPool.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetPoolListResponse {
    return {
      assetPool: globalThis.Array.isArray(object?.assetPool)
        ? object.assetPool.map((e: any) => AssetPool.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryGetPoolListResponse): unknown {
    const obj: any = {};
    if (message.assetPool?.length) {
      obj.assetPool = message.assetPool.map((e) => AssetPool.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPoolListResponse>, I>>(base?: I): QueryGetPoolListResponse {
    return QueryGetPoolListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPoolListResponse>, I>>(object: I): QueryGetPoolListResponse {
    const message = createBaseQueryGetPoolListResponse();
    message.assetPool = object.assetPool?.map((e) => AssetPool.fromPartial(e)) || [];
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** Queries a list of LoanTransaction items. */
  LoanTransaction(request: QueryGetLoanTransactionRequest): Promise<LoanTransactionResponse>;
  /** Queries all LoanTransaction items. */
  LoanTransactionAll(request: QueryAllLoanTransactionRequest): Promise<LoanTransactionAllResponse>;
  /** Queries a list of LoanObservation items. */
  LoanObservation(request: QueryGetLoanObservationRequest): Promise<LoanObservationResponse>;
  /** Queries all LoanObservationAll items. */
  LoanObservationAll(request: QueryAllLoanObservationRequest): Promise<LoanObservationAllResponse>;
  /** Queries a list of GetAvailableTransaction items. */
  GetAvailableTransaction(request: QueryGetAvailableTransactionRequest): Promise<QueryGetAvailableTransactionResponse>;
  /** Queries a list of ObserveVote items. */
  ObserveVote(request: QueryGetObserveVoteRequest): Promise<ObserveVoteResponse>;
  /** Queries all list of ObserveVote items. */
  ObserveVoteAll(request: QueryAllObserveVoteRequest): Promise<ObserveVoteAllResponse>;
  /** Queries a list of LoanEntity items. */
  LoanEntity(request: QueryGetLoanEntityRequest): Promise<QueryGetLoanEntityResponse>;
  LoanEntityAll(request: QueryAllLoanEntityRequest): Promise<QueryAllLoanEntityResponse>;
  GetAccountSummary(request: QueryGetAccountSummaryRequest): Promise<QueryGetAccountSummaryResponse>;
  /** Queries a list of GetAccountSuppliedAssets items. */
  GetAccountSuppliedAssets(
    request: QueryGetAccountSuppliedAssetsRequest,
  ): Promise<QueryGetAccountSuppliedAssetsResponse>;
  /** Queries a list of GetAccountBorrowedAssets items. */
  GetAccountBorrowedAssets(
    request: QueryGetAccountBorrowedAssetsRequest,
  ): Promise<QueryGetAccountBorrowedAssetsResponse>;
  /** Queries a list of GetPoolSummary items. */
  GetPoolSummary(request: QueryGetPoolSummaryRequest): Promise<QueryGetPoolSummaryResponse>;
  /** Queries a list of GetPoolList items. */
  GetPoolList(request: QueryGetPoolListRequest): Promise<QueryGetPoolListResponse>;
}

export const QueryServiceName = "cfprotocol.loan.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.LoanTransaction = this.LoanTransaction.bind(this);
    this.LoanTransactionAll = this.LoanTransactionAll.bind(this);
    this.LoanObservation = this.LoanObservation.bind(this);
    this.LoanObservationAll = this.LoanObservationAll.bind(this);
    this.GetAvailableTransaction = this.GetAvailableTransaction.bind(this);
    this.ObserveVote = this.ObserveVote.bind(this);
    this.ObserveVoteAll = this.ObserveVoteAll.bind(this);
    this.LoanEntity = this.LoanEntity.bind(this);
    this.LoanEntityAll = this.LoanEntityAll.bind(this);
    this.GetAccountSummary = this.GetAccountSummary.bind(this);
    this.GetAccountSuppliedAssets = this.GetAccountSuppliedAssets.bind(this);
    this.GetAccountBorrowedAssets = this.GetAccountBorrowedAssets.bind(this);
    this.GetPoolSummary = this.GetPoolSummary.bind(this);
    this.GetPoolList = this.GetPoolList.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  LoanTransaction(request: QueryGetLoanTransactionRequest): Promise<LoanTransactionResponse> {
    const data = QueryGetLoanTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanTransaction", data);
    return promise.then((data) => LoanTransactionResponse.decode(new BinaryReader(data)));
  }

  LoanTransactionAll(request: QueryAllLoanTransactionRequest): Promise<LoanTransactionAllResponse> {
    const data = QueryAllLoanTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanTransactionAll", data);
    return promise.then((data) => LoanTransactionAllResponse.decode(new BinaryReader(data)));
  }

  LoanObservation(request: QueryGetLoanObservationRequest): Promise<LoanObservationResponse> {
    const data = QueryGetLoanObservationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanObservation", data);
    return promise.then((data) => LoanObservationResponse.decode(new BinaryReader(data)));
  }

  LoanObservationAll(request: QueryAllLoanObservationRequest): Promise<LoanObservationAllResponse> {
    const data = QueryAllLoanObservationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanObservationAll", data);
    return promise.then((data) => LoanObservationAllResponse.decode(new BinaryReader(data)));
  }

  GetAvailableTransaction(request: QueryGetAvailableTransactionRequest): Promise<QueryGetAvailableTransactionResponse> {
    const data = QueryGetAvailableTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAvailableTransaction", data);
    return promise.then((data) => QueryGetAvailableTransactionResponse.decode(new BinaryReader(data)));
  }

  ObserveVote(request: QueryGetObserveVoteRequest): Promise<ObserveVoteResponse> {
    const data = QueryGetObserveVoteRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ObserveVote", data);
    return promise.then((data) => ObserveVoteResponse.decode(new BinaryReader(data)));
  }

  ObserveVoteAll(request: QueryAllObserveVoteRequest): Promise<ObserveVoteAllResponse> {
    const data = QueryAllObserveVoteRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ObserveVoteAll", data);
    return promise.then((data) => ObserveVoteAllResponse.decode(new BinaryReader(data)));
  }

  LoanEntity(request: QueryGetLoanEntityRequest): Promise<QueryGetLoanEntityResponse> {
    const data = QueryGetLoanEntityRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanEntity", data);
    return promise.then((data) => QueryGetLoanEntityResponse.decode(new BinaryReader(data)));
  }

  LoanEntityAll(request: QueryAllLoanEntityRequest): Promise<QueryAllLoanEntityResponse> {
    const data = QueryAllLoanEntityRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoanEntityAll", data);
    return promise.then((data) => QueryAllLoanEntityResponse.decode(new BinaryReader(data)));
  }

  GetAccountSummary(request: QueryGetAccountSummaryRequest): Promise<QueryGetAccountSummaryResponse> {
    const data = QueryGetAccountSummaryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccountSummary", data);
    return promise.then((data) => QueryGetAccountSummaryResponse.decode(new BinaryReader(data)));
  }

  GetAccountSuppliedAssets(
    request: QueryGetAccountSuppliedAssetsRequest,
  ): Promise<QueryGetAccountSuppliedAssetsResponse> {
    const data = QueryGetAccountSuppliedAssetsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccountSuppliedAssets", data);
    return promise.then((data) => QueryGetAccountSuppliedAssetsResponse.decode(new BinaryReader(data)));
  }

  GetAccountBorrowedAssets(
    request: QueryGetAccountBorrowedAssetsRequest,
  ): Promise<QueryGetAccountBorrowedAssetsResponse> {
    const data = QueryGetAccountBorrowedAssetsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccountBorrowedAssets", data);
    return promise.then((data) => QueryGetAccountBorrowedAssetsResponse.decode(new BinaryReader(data)));
  }

  GetPoolSummary(request: QueryGetPoolSummaryRequest): Promise<QueryGetPoolSummaryResponse> {
    const data = QueryGetPoolSummaryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPoolSummary", data);
    return promise.then((data) => QueryGetPoolSummaryResponse.decode(new BinaryReader(data)));
  }

  GetPoolList(request: QueryGetPoolListRequest): Promise<QueryGetPoolListResponse> {
    const data = QueryGetPoolListRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPoolList", data);
    return promise.then((data) => QueryGetPoolListResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
