// Accounmt
export const GET_ACCOUNT_SUMMARY = 'GET_ACCOUNT_SUMMARY'
export const GET_ACCOUNT_SUPPLIES = 'GET_ACCOUNT_SUPPLIES'
export const GET_ACCOUNT_BORROWED = 'GET_ACCOUNT_BORROWED'

// Pool
export const GET_POOL_SUMMARY = 'GET_POOL_SUMMARY'
export const GET_POOL_LIST = 'GET_POOL_LIST'

// Governance
export const GET_GOVERNANCE_SUMMARY = 'GET_GOVERNANCE_SUMMARY'
export const GET_GOVERNANCE_PROPOSALS = 'GET_GOVERNANCE_PROPOSALS'
export const GET_GOVERNANCE_PROPOSAL_DETAIL = 'GET_GOVERNANCE_PROPOSAL_DETAIL'
export const GET_GOVERNANCE_VOTES = 'GET_GOVERNANCE_VOTES'
export const GET_GOVERNANCE_VOTE_DETAIL = 'GET_GOVERNANCE_VOTE_DETAIL'

// Stake
export const GET_STAKE_SUMMARY = 'GET_STAKE_SUMMARY'