// Accounmt
export const GET_ACCOUNT_SUMMARY = 'GET_ACCOUNT_SUMMARY'
export const GET_ACCOUNT_SUPPLIES = 'GET_ACCOUNT_SUPPLIES'
export const GET_ACCOUNT_BORROWED = 'GET_ACCOUNT_BORROWED'

// Pool
export const GET_POOL_SUMMARY = 'GET_POOL_SUMMARY'
export const GET_POOL_LIST = 'GET_POOL_LIST'
export const GET_POOL_TSS_PUBLIC_KEY = 'GET_POOL_TSS_PUBLIC_KEY'
export const GET_POOL_LOCK_BALANCE = 'GET_POOL_LOCK_BALANCE'
export const GET_ASSET_LOCK_TRANSACTION = 'GET_ASSET_LOCK_TRANSACTION'
export const GET_ASSET_BORROW_TRANSACTION = 'GET_ASSET_BORROW_TRANSACTION'
export const GET_ASSET_SUPPLY_TRANSACTION = 'GET_ASSET_SUPPLY_TRANSACTION'
export const GET_MAX_INTEREST_RATE = 'GET_MAX_INTEREST_RATE'
export const GET_LOAN_RATE = 'GET_LOAN_RATE'
export const GET_ASSET_PROFILE = 'GET_ASSET_PROFILE'
export const GET_LOAN_ENTITY = 'GET_LOAN_ENTITY'
export const GET_REPAY_ESTIMATED_AMOUNT = 'GET_REPAY_ESTIMATED_AMOUNT'

// Governance
export const GET_GOVERNANCE_SUMMARY = 'GET_GOVERNANCE_SUMMARY'
export const GET_GOVERNANCE_PROPOSALS = 'GET_GOVERNANCE_PROPOSALS'
export const GET_GOVERNANCE_PROPOSAL_DETAIL = 'GET_GOVERNANCE_PROPOSAL_DETAIL'
export const GET_GOVERNANCE_VOTES = 'GET_GOVERNANCE_VOTES'
export const GET_GOVERNANCE_VOTE_DETAIL = 'GET_GOVERNANCE_VOTE_DETAIL'

// Stake
export const GET_STAKE_SUMMARY = 'GET_STAKE_SUMMARY'
export const GET_STAKE_ALL_VALIDATORS = 'GET_STAKE_ALL_VALIDATORS'
export const GET_STAKE_ALL_DELEGATIONS = 'GET_STAKE_ALL_DELEGATIONS'
// Chain 
export const GET_BTC_BALANCE = 'GET_BTC_BALANCE'