export { default as BackIMG } from './backImg.png'
export { default as PhantomWallet } from './wallet.phantom.png'
export { default as InverseWallet } from './wallet.inverse.png'
export { default as UnisatWallet } from './wallet.unisat.png'
export { default as MetamastWallet } from './wallet.metamask.png'
export { default as KelprWallet } from './wallet.kelpr.png'
export { default as OkxWallet } from './wallet.okx.png'
export { default as WalletConnect } from './wallet.connect.png'
export { default as WarningImg } from './warning.png'
export { default as SuccessImg } from './success.png'
export { default as CancelImg } from './cancel.png'

export { default as WalletImg } from './walletImg.png'
export { default as BitcoinIMG } from './btc.png'
export { default as EthereumIMG } from './eth.png'
export { default as USDCIMG } from './usdc.png'
