// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/chain/stake_summary.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.chain";

/** StakeSummary defines the summary of the staking information */
export interface StakeSummary {
  user: string;
  userStaked: string;
  cfnStakeApr: string;
  dailyEmission: string;
  totalStaked: string;
}

function createBaseStakeSummary(): StakeSummary {
  return { user: "", userStaked: "", cfnStakeApr: "", dailyEmission: "", totalStaked: "" };
}

export const StakeSummary: MessageFns<StakeSummary> = {
  encode(message: StakeSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    if (message.userStaked !== "") {
      writer.uint32(18).string(message.userStaked);
    }
    if (message.cfnStakeApr !== "") {
      writer.uint32(26).string(message.cfnStakeApr);
    }
    if (message.dailyEmission !== "") {
      writer.uint32(34).string(message.dailyEmission);
    }
    if (message.totalStaked !== "") {
      writer.uint32(42).string(message.totalStaked);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StakeSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStakeSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.userStaked = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.cfnStakeApr = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.dailyEmission = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.totalStaked = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StakeSummary {
    return {
      user: isSet(object.user) ? globalThis.String(object.user) : "",
      userStaked: isSet(object.userStaked) ? globalThis.String(object.userStaked) : "",
      cfnStakeApr: isSet(object.cfnStakeApr) ? globalThis.String(object.cfnStakeApr) : "",
      dailyEmission: isSet(object.dailyEmission) ? globalThis.String(object.dailyEmission) : "",
      totalStaked: isSet(object.totalStaked) ? globalThis.String(object.totalStaked) : "",
    };
  },

  toJSON(message: StakeSummary): unknown {
    const obj: any = {};
    if (message.user !== "") {
      obj.user = message.user;
    }
    if (message.userStaked !== "") {
      obj.userStaked = message.userStaked;
    }
    if (message.cfnStakeApr !== "") {
      obj.cfnStakeApr = message.cfnStakeApr;
    }
    if (message.dailyEmission !== "") {
      obj.dailyEmission = message.dailyEmission;
    }
    if (message.totalStaked !== "") {
      obj.totalStaked = message.totalStaked;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StakeSummary>, I>>(base?: I): StakeSummary {
    return StakeSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StakeSummary>, I>>(object: I): StakeSummary {
    const message = createBaseStakeSummary();
    message.user = object.user ?? "";
    message.userStaked = object.userStaked ?? "";
    message.cfnStakeApr = object.cfnStakeApr ?? "";
    message.dailyEmission = object.dailyEmission ?? "";
    message.totalStaked = object.totalStaked ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
