// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/lock/supply_hash_observation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.lock";

export interface SupplyHashObservation {
  id: number;
  voter: string;
  txHash: string;
  from: string;
  to: string;
  amount: string;
  txTime: string;
  chainId: string;
  used: boolean;
  cfTxId: number;
  succeed: boolean;
  payType: string;
  failReason: string;
  reserved: string;
}

function createBaseSupplyHashObservation(): SupplyHashObservation {
  return {
    id: 0,
    voter: "",
    txHash: "",
    from: "",
    to: "",
    amount: "",
    txTime: "",
    chainId: "",
    used: false,
    cfTxId: 0,
    succeed: false,
    payType: "",
    failReason: "",
    reserved: "",
  };
}

export const SupplyHashObservation: MessageFns<SupplyHashObservation> = {
  encode(message: SupplyHashObservation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.voter !== "") {
      writer.uint32(18).string(message.voter);
    }
    if (message.txHash !== "") {
      writer.uint32(26).string(message.txHash);
    }
    if (message.from !== "") {
      writer.uint32(34).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(42).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    if (message.txTime !== "") {
      writer.uint32(58).string(message.txTime);
    }
    if (message.chainId !== "") {
      writer.uint32(66).string(message.chainId);
    }
    if (message.used !== false) {
      writer.uint32(72).bool(message.used);
    }
    if (message.cfTxId !== 0) {
      writer.uint32(80).uint64(message.cfTxId);
    }
    if (message.succeed !== false) {
      writer.uint32(88).bool(message.succeed);
    }
    if (message.payType !== "") {
      writer.uint32(98).string(message.payType);
    }
    if (message.failReason !== "") {
      writer.uint32(106).string(message.failReason);
    }
    if (message.reserved !== "") {
      writer.uint32(114).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SupplyHashObservation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSupplyHashObservation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.voter = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.txHash = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.from = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.to = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.txTime = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.chainId = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.used = reader.bool();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.cfTxId = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.succeed = reader.bool();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.payType = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.failReason = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SupplyHashObservation {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      voter: isSet(object.voter) ? globalThis.String(object.voter) : "",
      txHash: isSet(object.txHash) ? globalThis.String(object.txHash) : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      txTime: isSet(object.txTime) ? globalThis.String(object.txTime) : "",
      chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "",
      used: isSet(object.used) ? globalThis.Boolean(object.used) : false,
      cfTxId: isSet(object.cfTxId) ? globalThis.Number(object.cfTxId) : 0,
      succeed: isSet(object.succeed) ? globalThis.Boolean(object.succeed) : false,
      payType: isSet(object.payType) ? globalThis.String(object.payType) : "",
      failReason: isSet(object.failReason) ? globalThis.String(object.failReason) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: SupplyHashObservation): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.voter !== "") {
      obj.voter = message.voter;
    }
    if (message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.txTime !== "") {
      obj.txTime = message.txTime;
    }
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.used !== false) {
      obj.used = message.used;
    }
    if (message.cfTxId !== 0) {
      obj.cfTxId = Math.round(message.cfTxId);
    }
    if (message.succeed !== false) {
      obj.succeed = message.succeed;
    }
    if (message.payType !== "") {
      obj.payType = message.payType;
    }
    if (message.failReason !== "") {
      obj.failReason = message.failReason;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SupplyHashObservation>, I>>(base?: I): SupplyHashObservation {
    return SupplyHashObservation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SupplyHashObservation>, I>>(object: I): SupplyHashObservation {
    const message = createBaseSupplyHashObservation();
    message.id = object.id ?? 0;
    message.voter = object.voter ?? "";
    message.txHash = object.txHash ?? "";
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.txTime = object.txTime ?? "";
    message.chainId = object.chainId ?? "";
    message.used = object.used ?? false;
    message.cfTxId = object.cfTxId ?? 0;
    message.succeed = object.succeed ?? false;
    message.payType = object.payType ?? "";
    message.failReason = object.failReason ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
