// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/tss/tx.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "cfprotocol.tss";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /**
   * params defines the module parameters to update.
   * NOTE: All parameters must be supplied.
   */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgAddPubkey is the Msg/MsgAddPubkey request type. */
export interface MsgAddPubkey {
  creator: string;
  pubkey: string;
}

/**
 * MsgAddPubkeyResponse defines the response structure for executing a
 * MsgAddPubkey message.
 */
export interface MsgAddPubkeyResponse {
  code: string;
  msg: string;
}

/** MsgUpdatePubkey is the Msg/MsgUpdatePubkey request type. */
export interface MsgUpdatePubkey {
  creator: string;
  pubkeys: string[];
  keygenBlockHeight: number;
}

/**
 * MsgUpdatePubkeyResponse defines the response structure for executing a
 * MsgUpdatePubkey message.
 */
export interface MsgUpdatePubkeyResponse {
  code: string;
  msg: string;
}

/** MsgUpdateTssPubkey is the Msg/MsgUpdateTssPubkey request type. */
export interface MsgUpdateTssPubkey {
  creator: string;
  tssPubkey: string;
  ecdsa: string;
  bitcoin: string;
  reserved: string;
}

/**
 * MsgUpdateTssPubkeyResponse defines the response structure for executing a
 * MsgUpdateTssPubkey message.
 */
export interface MsgUpdateTssPubkeyResponse {
  code: string;
  msg: string;
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgAddPubkey(): MsgAddPubkey {
  return { creator: "", pubkey: "" };
}

export const MsgAddPubkey: MessageFns<MsgAddPubkey> = {
  encode(message: MsgAddPubkey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.pubkey !== "") {
      writer.uint32(18).string(message.pubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddPubkey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddPubkey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pubkey = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddPubkey {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
    };
  },

  toJSON(message: MsgAddPubkey): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddPubkey>, I>>(base?: I): MsgAddPubkey {
    return MsgAddPubkey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddPubkey>, I>>(object: I): MsgAddPubkey {
    const message = createBaseMsgAddPubkey();
    message.creator = object.creator ?? "";
    message.pubkey = object.pubkey ?? "";
    return message;
  },
};

function createBaseMsgAddPubkeyResponse(): MsgAddPubkeyResponse {
  return { code: "", msg: "" };
}

export const MsgAddPubkeyResponse: MessageFns<MsgAddPubkeyResponse> = {
  encode(message: MsgAddPubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddPubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddPubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddPubkeyResponse {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: MsgAddPubkeyResponse): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddPubkeyResponse>, I>>(base?: I): MsgAddPubkeyResponse {
    return MsgAddPubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddPubkeyResponse>, I>>(object: I): MsgAddPubkeyResponse {
    const message = createBaseMsgAddPubkeyResponse();
    message.code = object.code ?? "";
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseMsgUpdatePubkey(): MsgUpdatePubkey {
  return { creator: "", pubkeys: [], keygenBlockHeight: 0 };
}

export const MsgUpdatePubkey: MessageFns<MsgUpdatePubkey> = {
  encode(message: MsgUpdatePubkey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    for (const v of message.pubkeys) {
      writer.uint32(18).string(v!);
    }
    if (message.keygenBlockHeight !== 0) {
      writer.uint32(24).uint64(message.keygenBlockHeight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdatePubkey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdatePubkey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pubkeys.push(reader.string());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.keygenBlockHeight = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdatePubkey {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      pubkeys: globalThis.Array.isArray(object?.pubkeys) ? object.pubkeys.map((e: any) => globalThis.String(e)) : [],
      keygenBlockHeight: isSet(object.keygenBlockHeight) ? globalThis.Number(object.keygenBlockHeight) : 0,
    };
  },

  toJSON(message: MsgUpdatePubkey): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.pubkeys?.length) {
      obj.pubkeys = message.pubkeys;
    }
    if (message.keygenBlockHeight !== 0) {
      obj.keygenBlockHeight = Math.round(message.keygenBlockHeight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdatePubkey>, I>>(base?: I): MsgUpdatePubkey {
    return MsgUpdatePubkey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdatePubkey>, I>>(object: I): MsgUpdatePubkey {
    const message = createBaseMsgUpdatePubkey();
    message.creator = object.creator ?? "";
    message.pubkeys = object.pubkeys?.map((e) => e) || [];
    message.keygenBlockHeight = object.keygenBlockHeight ?? 0;
    return message;
  },
};

function createBaseMsgUpdatePubkeyResponse(): MsgUpdatePubkeyResponse {
  return { code: "", msg: "" };
}

export const MsgUpdatePubkeyResponse: MessageFns<MsgUpdatePubkeyResponse> = {
  encode(message: MsgUpdatePubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdatePubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdatePubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdatePubkeyResponse {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: MsgUpdatePubkeyResponse): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdatePubkeyResponse>, I>>(base?: I): MsgUpdatePubkeyResponse {
    return MsgUpdatePubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdatePubkeyResponse>, I>>(object: I): MsgUpdatePubkeyResponse {
    const message = createBaseMsgUpdatePubkeyResponse();
    message.code = object.code ?? "";
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseMsgUpdateTssPubkey(): MsgUpdateTssPubkey {
  return { creator: "", tssPubkey: "", ecdsa: "", bitcoin: "", reserved: "" };
}

export const MsgUpdateTssPubkey: MessageFns<MsgUpdateTssPubkey> = {
  encode(message: MsgUpdateTssPubkey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.tssPubkey !== "") {
      writer.uint32(18).string(message.tssPubkey);
    }
    if (message.ecdsa !== "") {
      writer.uint32(26).string(message.ecdsa);
    }
    if (message.bitcoin !== "") {
      writer.uint32(34).string(message.bitcoin);
    }
    if (message.reserved !== "") {
      writer.uint32(42).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateTssPubkey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateTssPubkey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.tssPubkey = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.ecdsa = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.bitcoin = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateTssPubkey {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      tssPubkey: isSet(object.tssPubkey) ? globalThis.String(object.tssPubkey) : "",
      ecdsa: isSet(object.ecdsa) ? globalThis.String(object.ecdsa) : "",
      bitcoin: isSet(object.bitcoin) ? globalThis.String(object.bitcoin) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: MsgUpdateTssPubkey): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.tssPubkey !== "") {
      obj.tssPubkey = message.tssPubkey;
    }
    if (message.ecdsa !== "") {
      obj.ecdsa = message.ecdsa;
    }
    if (message.bitcoin !== "") {
      obj.bitcoin = message.bitcoin;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateTssPubkey>, I>>(base?: I): MsgUpdateTssPubkey {
    return MsgUpdateTssPubkey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateTssPubkey>, I>>(object: I): MsgUpdateTssPubkey {
    const message = createBaseMsgUpdateTssPubkey();
    message.creator = object.creator ?? "";
    message.tssPubkey = object.tssPubkey ?? "";
    message.ecdsa = object.ecdsa ?? "";
    message.bitcoin = object.bitcoin ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

function createBaseMsgUpdateTssPubkeyResponse(): MsgUpdateTssPubkeyResponse {
  return { code: "", msg: "" };
}

export const MsgUpdateTssPubkeyResponse: MessageFns<MsgUpdateTssPubkeyResponse> = {
  encode(message: MsgUpdateTssPubkeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateTssPubkeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateTssPubkeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateTssPubkeyResponse {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: MsgUpdateTssPubkeyResponse): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateTssPubkeyResponse>, I>>(base?: I): MsgUpdateTssPubkeyResponse {
    return MsgUpdateTssPubkeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateTssPubkeyResponse>, I>>(object: I): MsgUpdateTssPubkeyResponse {
    const message = createBaseMsgUpdateTssPubkeyResponse();
    message.code = object.code ?? "";
    message.msg = object.msg ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** AddPubkey defines an operation for add public key */
  AddPubkey(request: MsgAddPubkey): Promise<MsgAddPubkeyResponse>;
  /** UpdatePubkey defines an operation for update public keys */
  UpdatePubkey(request: MsgUpdatePubkey): Promise<MsgUpdatePubkeyResponse>;
  /** UpdateTssPubkey defines an operation for update tss result */
  UpdateTssPubkey(request: MsgUpdateTssPubkey): Promise<MsgUpdateTssPubkeyResponse>;
}

export const MsgServiceName = "cfprotocol.tss.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.AddPubkey = this.AddPubkey.bind(this);
    this.UpdatePubkey = this.UpdatePubkey.bind(this);
    this.UpdateTssPubkey = this.UpdateTssPubkey.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  AddPubkey(request: MsgAddPubkey): Promise<MsgAddPubkeyResponse> {
    const data = MsgAddPubkey.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddPubkey", data);
    return promise.then((data) => MsgAddPubkeyResponse.decode(new BinaryReader(data)));
  }

  UpdatePubkey(request: MsgUpdatePubkey): Promise<MsgUpdatePubkeyResponse> {
    const data = MsgUpdatePubkey.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdatePubkey", data);
    return promise.then((data) => MsgUpdatePubkeyResponse.decode(new BinaryReader(data)));
  }

  UpdateTssPubkey(request: MsgUpdateTssPubkey): Promise<MsgUpdateTssPubkeyResponse> {
    const data = MsgUpdateTssPubkey.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateTssPubkey", data);
    return promise.then((data) => MsgUpdateTssPubkeyResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
