// @ts-nocheck
// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/cfprotocol/asset/tx";
import { MsgUpdateParamsResponse } from "./types/cfprotocol/asset/tx";
import { MsgCreateAssetProfileResponse } from "./types/cfprotocol/asset/tx";
import { MsgUpdateAssetProfileResponse } from "./types/cfprotocol/asset/tx";
import { MsgDeleteAssetProfileResponse } from "./types/cfprotocol/asset/tx";
import { QueryParamsRequest } from "./types/cfprotocol/asset/query";
import { QueryParamsResponse } from "./types/cfprotocol/asset/query";
import { MsgDeleteAssetProfile } from "./types/cfprotocol/asset/tx";
import { AssetProfile } from "./types/cfprotocol/asset/profile";
import { MsgCreateAssetProfile } from "./types/cfprotocol/asset/tx";
import { MsgUpdateAssetProfile } from "./types/cfprotocol/asset/tx";
import { GenesisState } from "./types/cfprotocol/asset/genesis";
import { QueryAssetProfileAllRequest } from "./types/cfprotocol/asset/query";
import { QueryAssetProfileAllResponse } from "./types/cfprotocol/asset/query";
import { Params } from "./types/cfprotocol/asset/params";
import { QueryAssetProfileRequest } from "./types/cfprotocol/asset/query";
import { QueryAssetProfileResponse } from "./types/cfprotocol/asset/query";


export { MsgUpdateParams, MsgUpdateParamsResponse, MsgCreateAssetProfileResponse, MsgUpdateAssetProfileResponse, MsgDeleteAssetProfileResponse, QueryParamsRequest, QueryParamsResponse, MsgDeleteAssetProfile, AssetProfile, MsgCreateAssetProfile, MsgUpdateAssetProfile, GenesisState, QueryAssetProfileAllRequest, QueryAssetProfileAllResponse, Params, QueryAssetProfileRequest, QueryAssetProfileResponse };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateAssetProfileResponseParams = {
  value: MsgCreateAssetProfileResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateAssetProfileResponseParams = {
  value: MsgUpdateAssetProfileResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteAssetProfileResponseParams = {
  value: MsgDeleteAssetProfileResponse,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsRequestParams = {
  value: QueryParamsRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryParamsResponseParams = {
  value: QueryParamsResponse,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteAssetProfileParams = {
  value: MsgDeleteAssetProfile,
  fee?: StdFee,
  memo?: string
};

type sendAssetProfileParams = {
  value: AssetProfile,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateAssetProfileParams = {
  value: MsgCreateAssetProfile,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateAssetProfileParams = {
  value: MsgUpdateAssetProfile,
  fee?: StdFee,
  memo?: string
};

type sendGenesisStateParams = {
  value: GenesisState,
  fee?: StdFee,
  memo?: string
};

type sendQueryAssetProfileAllRequestParams = {
  value: QueryAssetProfileAllRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAssetProfileAllResponseParams = {
  value: QueryAssetProfileAllResponse,
  fee?: StdFee,
  memo?: string
};

type sendParamsParams = {
  value: Params,
  fee?: StdFee,
  memo?: string
};

type sendQueryAssetProfileRequestParams = {
  value: QueryAssetProfileRequest,
  fee?: StdFee,
  memo?: string
};

type sendQueryAssetProfileResponseParams = {
  value: QueryAssetProfileResponse,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgUpdateParamsResponseParams = {
  value: MsgUpdateParamsResponse,
};

type msgCreateAssetProfileResponseParams = {
  value: MsgCreateAssetProfileResponse,
};

type msgUpdateAssetProfileResponseParams = {
  value: MsgUpdateAssetProfileResponse,
};

type msgDeleteAssetProfileResponseParams = {
  value: MsgDeleteAssetProfileResponse,
};

type queryParamsRequestParams = {
  value: QueryParamsRequest,
};

type queryParamsResponseParams = {
  value: QueryParamsResponse,
};

type msgDeleteAssetProfileParams = {
  value: MsgDeleteAssetProfile,
};

type assetProfileParams = {
  value: AssetProfile,
};

type msgCreateAssetProfileParams = {
  value: MsgCreateAssetProfile,
};

type msgUpdateAssetProfileParams = {
  value: MsgUpdateAssetProfile,
};

type genesisStateParams = {
  value: GenesisState,
};

type queryAssetProfileAllRequestParams = {
  value: QueryAssetProfileAllRequest,
};

type queryAssetProfileAllResponseParams = {
  value: QueryAssetProfileAllResponse,
};

type paramsParams = {
  value: Params,
};

type queryAssetProfileRequestParams = {
  value: QueryAssetProfileRequest,
};

type queryAssetProfileResponseParams = {
  value: QueryAssetProfileResponse,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParamsResponse({ value, fee, memo }: sendMsgUpdateParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParamsResponse({ value: MsgUpdateParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateAssetProfileResponse({ value, fee, memo }: sendMsgCreateAssetProfileResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateAssetProfileResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateAssetProfileResponse({ value: MsgCreateAssetProfileResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateAssetProfileResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateAssetProfileResponse({ value, fee, memo }: sendMsgUpdateAssetProfileResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateAssetProfileResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateAssetProfileResponse({ value: MsgUpdateAssetProfileResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateAssetProfileResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteAssetProfileResponse({ value, fee, memo }: sendMsgDeleteAssetProfileResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteAssetProfileResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteAssetProfileResponse({ value: MsgDeleteAssetProfileResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteAssetProfileResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsRequest({ value, fee, memo }: sendQueryParamsRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsRequest({ value: QueryParamsRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryParamsResponse({ value, fee, memo }: sendQueryParamsResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryParamsResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryParamsResponse({ value: QueryParamsResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryParamsResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteAssetProfile({ value, fee, memo }: sendMsgDeleteAssetProfileParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteAssetProfile: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteAssetProfile({ value: MsgDeleteAssetProfile.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteAssetProfile: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendAssetProfile({ value, fee, memo }: sendAssetProfileParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendAssetProfile: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.assetProfile({ value: AssetProfile.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendAssetProfile: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateAssetProfile({ value, fee, memo }: sendMsgCreateAssetProfileParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateAssetProfile: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateAssetProfile({ value: MsgCreateAssetProfile.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateAssetProfile: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateAssetProfile({ value, fee, memo }: sendMsgUpdateAssetProfileParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateAssetProfile: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateAssetProfile({ value: MsgUpdateAssetProfile.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateAssetProfile: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendGenesisState({ value, fee, memo }: sendGenesisStateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendGenesisState: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.genesisState({ value: GenesisState.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendGenesisState: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAssetProfileAllRequest({ value, fee, memo }: sendQueryAssetProfileAllRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAssetProfileAllRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAssetProfileAllRequest({ value: QueryAssetProfileAllRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAssetProfileAllRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAssetProfileAllResponse({ value, fee, memo }: sendQueryAssetProfileAllResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAssetProfileAllResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAssetProfileAllResponse({ value: QueryAssetProfileAllResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAssetProfileAllResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendParams({ value, fee, memo }: sendParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.params({ value: Params.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAssetProfileRequest({ value, fee, memo }: sendQueryAssetProfileRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAssetProfileRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAssetProfileRequest({ value: QueryAssetProfileRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAssetProfileRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendQueryAssetProfileResponse({ value, fee, memo }: sendQueryAssetProfileResponseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendQueryAssetProfileResponse: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.queryAssetProfileResponse({ value: QueryAssetProfileResponse.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendQueryAssetProfileResponse: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParamsResponse({ value }: msgUpdateParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgUpdateParamsResponse", value: MsgUpdateParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgCreateAssetProfileResponse({ value }: msgCreateAssetProfileResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgCreateAssetProfileResponse", value: MsgCreateAssetProfileResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateAssetProfileResponse: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateAssetProfileResponse({ value }: msgUpdateAssetProfileResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgUpdateAssetProfileResponse", value: MsgUpdateAssetProfileResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateAssetProfileResponse: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteAssetProfileResponse({ value }: msgDeleteAssetProfileResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgDeleteAssetProfileResponse", value: MsgDeleteAssetProfileResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteAssetProfileResponse: Could not create message: ' + e.message)
			}
		},
		
		queryParamsRequest({ value }: queryParamsRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryParamsRequest", value: QueryParamsRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsRequest: Could not create message: ' + e.message)
			}
		},
		
		queryParamsResponse({ value }: queryParamsResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryParamsResponse", value: QueryParamsResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryParamsResponse: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteAssetProfile({ value }: msgDeleteAssetProfileParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgDeleteAssetProfile", value: MsgDeleteAssetProfile.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteAssetProfile: Could not create message: ' + e.message)
			}
		},
		
		assetProfile({ value }: assetProfileParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.AssetProfile", value: AssetProfile.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:AssetProfile: Could not create message: ' + e.message)
			}
		},
		
		msgCreateAssetProfile({ value }: msgCreateAssetProfileParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgCreateAssetProfile", value: MsgCreateAssetProfile.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateAssetProfile: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateAssetProfile({ value }: msgUpdateAssetProfileParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.MsgUpdateAssetProfile", value: MsgUpdateAssetProfile.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateAssetProfile: Could not create message: ' + e.message)
			}
		},
		
		genesisState({ value }: genesisStateParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.GenesisState", value: GenesisState.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:GenesisState: Could not create message: ' + e.message)
			}
		},
		
		queryAssetProfileAllRequest({ value }: queryAssetProfileAllRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryAssetProfileAllRequest", value: QueryAssetProfileAllRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAssetProfileAllRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAssetProfileAllResponse({ value }: queryAssetProfileAllResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryAssetProfileAllResponse", value: QueryAssetProfileAllResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAssetProfileAllResponse: Could not create message: ' + e.message)
			}
		},
		
		params({ value }: paramsParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.Params", value: Params.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:Params: Could not create message: ' + e.message)
			}
		},
		
		queryAssetProfileRequest({ value }: queryAssetProfileRequestParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryAssetProfileRequest", value: QueryAssetProfileRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAssetProfileRequest: Could not create message: ' + e.message)
			}
		},
		
		queryAssetProfileResponse({ value }: queryAssetProfileResponseParams): EncodeObject {
			try {
				return { typeUrl: "/cfprotocol.asset.QueryAssetProfileResponse", value: QueryAssetProfileResponse.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:QueryAssetProfileResponse: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			CfprotocolAsset: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;