// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/lock/supply_tss_observation.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.lock";

/** SupplyTransaction defines the supply transaction */
export interface SupplyTssObservation {
  id: number;
  voter: string;
  txId: number;
  txTssHash: string;
  tssSucceed: boolean;
  errReason: string;
  used: boolean;
}

function createBaseSupplyTssObservation(): SupplyTssObservation {
  return { id: 0, voter: "", txId: 0, txTssHash: "", tssSucceed: false, errReason: "", used: false };
}

export const SupplyTssObservation: MessageFns<SupplyTssObservation> = {
  encode(message: SupplyTssObservation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.voter !== "") {
      writer.uint32(18).string(message.voter);
    }
    if (message.txId !== 0) {
      writer.uint32(24).uint64(message.txId);
    }
    if (message.txTssHash !== "") {
      writer.uint32(34).string(message.txTssHash);
    }
    if (message.tssSucceed !== false) {
      writer.uint32(40).bool(message.tssSucceed);
    }
    if (message.errReason !== "") {
      writer.uint32(50).string(message.errReason);
    }
    if (message.used !== false) {
      writer.uint32(56).bool(message.used);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SupplyTssObservation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSupplyTssObservation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.voter = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.txId = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.txTssHash = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.tssSucceed = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.errReason = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.used = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SupplyTssObservation {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      voter: isSet(object.voter) ? globalThis.String(object.voter) : "",
      txId: isSet(object.txId) ? globalThis.Number(object.txId) : 0,
      txTssHash: isSet(object.txTssHash) ? globalThis.String(object.txTssHash) : "",
      tssSucceed: isSet(object.tssSucceed) ? globalThis.Boolean(object.tssSucceed) : false,
      errReason: isSet(object.errReason) ? globalThis.String(object.errReason) : "",
      used: isSet(object.used) ? globalThis.Boolean(object.used) : false,
    };
  },

  toJSON(message: SupplyTssObservation): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.voter !== "") {
      obj.voter = message.voter;
    }
    if (message.txId !== 0) {
      obj.txId = Math.round(message.txId);
    }
    if (message.txTssHash !== "") {
      obj.txTssHash = message.txTssHash;
    }
    if (message.tssSucceed !== false) {
      obj.tssSucceed = message.tssSucceed;
    }
    if (message.errReason !== "") {
      obj.errReason = message.errReason;
    }
    if (message.used !== false) {
      obj.used = message.used;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SupplyTssObservation>, I>>(base?: I): SupplyTssObservation {
    return SupplyTssObservation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SupplyTssObservation>, I>>(object: I): SupplyTssObservation {
    const message = createBaseSupplyTssObservation();
    message.id = object.id ?? 0;
    message.voter = object.voter ?? "";
    message.txId = object.txId ?? 0;
    message.txTssHash = object.txTssHash ?? "";
    message.tssSucceed = object.tssSucceed ?? false;
    message.errReason = object.errReason ?? "";
    message.used = object.used ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
