// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/transaction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.loan";

/** LoanTransaction defines the loan transaction entity */
export interface LoanTransaction {
  id: number;
  creator: string;
  collateralId: number;
  collateralSymbol: string;
  collateralAmount: string;
  loanDuration: number;
  interestRate: string;
  loanRate: string;
  oraclePrice: string;
  loanAmount: string;
  status: string;
  releaseHash: string;
  confirmedBlockHash: string;
  time: number;
  failReason: string;
  releaseFailCount: number;
  processing: boolean;
  tssMsgId: string;
  timestamp: string;
  handleId: number;
  loanAddress: string;
  reserved: string;
}

function createBaseLoanTransaction(): LoanTransaction {
  return {
    id: 0,
    creator: "",
    collateralId: 0,
    collateralSymbol: "",
    collateralAmount: "",
    loanDuration: 0,
    interestRate: "",
    loanRate: "",
    oraclePrice: "",
    loanAmount: "",
    status: "",
    releaseHash: "",
    confirmedBlockHash: "",
    time: 0,
    failReason: "",
    releaseFailCount: 0,
    processing: false,
    tssMsgId: "",
    timestamp: "",
    handleId: 0,
    loanAddress: "",
    reserved: "",
  };
}

export const LoanTransaction: MessageFns<LoanTransaction> = {
  encode(message: LoanTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    if (message.collateralId !== 0) {
      writer.uint32(24).uint64(message.collateralId);
    }
    if (message.collateralSymbol !== "") {
      writer.uint32(34).string(message.collateralSymbol);
    }
    if (message.collateralAmount !== "") {
      writer.uint32(42).string(message.collateralAmount);
    }
    if (message.loanDuration !== 0) {
      writer.uint32(48).uint64(message.loanDuration);
    }
    if (message.interestRate !== "") {
      writer.uint32(58).string(message.interestRate);
    }
    if (message.loanRate !== "") {
      writer.uint32(66).string(message.loanRate);
    }
    if (message.oraclePrice !== "") {
      writer.uint32(74).string(message.oraclePrice);
    }
    if (message.loanAmount !== "") {
      writer.uint32(82).string(message.loanAmount);
    }
    if (message.status !== "") {
      writer.uint32(90).string(message.status);
    }
    if (message.releaseHash !== "") {
      writer.uint32(98).string(message.releaseHash);
    }
    if (message.confirmedBlockHash !== "") {
      writer.uint32(106).string(message.confirmedBlockHash);
    }
    if (message.time !== 0) {
      writer.uint32(112).uint64(message.time);
    }
    if (message.failReason !== "") {
      writer.uint32(122).string(message.failReason);
    }
    if (message.releaseFailCount !== 0) {
      writer.uint32(128).uint64(message.releaseFailCount);
    }
    if (message.processing !== false) {
      writer.uint32(136).bool(message.processing);
    }
    if (message.tssMsgId !== "") {
      writer.uint32(146).string(message.tssMsgId);
    }
    if (message.timestamp !== "") {
      writer.uint32(154).string(message.timestamp);
    }
    if (message.handleId !== 0) {
      writer.uint32(160).uint64(message.handleId);
    }
    if (message.loanAddress !== "") {
      writer.uint32(170).string(message.loanAddress);
    }
    if (message.reserved !== "") {
      writer.uint32(178).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoanTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoanTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.collateralId = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.collateralSymbol = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.collateralAmount = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.loanDuration = longToNumber(reader.uint64());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.interestRate = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.loanRate = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.oraclePrice = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.loanAmount = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.status = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.releaseHash = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.confirmedBlockHash = reader.string();
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.time = longToNumber(reader.uint64());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.failReason = reader.string();
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.releaseFailCount = longToNumber(reader.uint64());
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.processing = reader.bool();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.tssMsgId = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        case 20:
          if (tag !== 160) {
            break;
          }

          message.handleId = longToNumber(reader.uint64());
          continue;
        case 21:
          if (tag !== 170) {
            break;
          }

          message.loanAddress = reader.string();
          continue;
        case 22:
          if (tag !== 178) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoanTransaction {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      collateralId: isSet(object.collateralId) ? globalThis.Number(object.collateralId) : 0,
      collateralSymbol: isSet(object.collateralSymbol) ? globalThis.String(object.collateralSymbol) : "",
      collateralAmount: isSet(object.collateralAmount) ? globalThis.String(object.collateralAmount) : "",
      loanDuration: isSet(object.loanDuration) ? globalThis.Number(object.loanDuration) : 0,
      interestRate: isSet(object.interestRate) ? globalThis.String(object.interestRate) : "",
      loanRate: isSet(object.loanRate) ? globalThis.String(object.loanRate) : "",
      oraclePrice: isSet(object.oraclePrice) ? globalThis.String(object.oraclePrice) : "",
      loanAmount: isSet(object.loanAmount) ? globalThis.String(object.loanAmount) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      releaseHash: isSet(object.releaseHash) ? globalThis.String(object.releaseHash) : "",
      confirmedBlockHash: isSet(object.confirmedBlockHash) ? globalThis.String(object.confirmedBlockHash) : "",
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      failReason: isSet(object.failReason) ? globalThis.String(object.failReason) : "",
      releaseFailCount: isSet(object.releaseFailCount) ? globalThis.Number(object.releaseFailCount) : 0,
      processing: isSet(object.processing) ? globalThis.Boolean(object.processing) : false,
      tssMsgId: isSet(object.tssMsgId) ? globalThis.String(object.tssMsgId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      handleId: isSet(object.handleId) ? globalThis.Number(object.handleId) : 0,
      loanAddress: isSet(object.loanAddress) ? globalThis.String(object.loanAddress) : "",
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: LoanTransaction): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.collateralId !== 0) {
      obj.collateralId = Math.round(message.collateralId);
    }
    if (message.collateralSymbol !== "") {
      obj.collateralSymbol = message.collateralSymbol;
    }
    if (message.collateralAmount !== "") {
      obj.collateralAmount = message.collateralAmount;
    }
    if (message.loanDuration !== 0) {
      obj.loanDuration = Math.round(message.loanDuration);
    }
    if (message.interestRate !== "") {
      obj.interestRate = message.interestRate;
    }
    if (message.loanRate !== "") {
      obj.loanRate = message.loanRate;
    }
    if (message.oraclePrice !== "") {
      obj.oraclePrice = message.oraclePrice;
    }
    if (message.loanAmount !== "") {
      obj.loanAmount = message.loanAmount;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.releaseHash !== "") {
      obj.releaseHash = message.releaseHash;
    }
    if (message.confirmedBlockHash !== "") {
      obj.confirmedBlockHash = message.confirmedBlockHash;
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.failReason !== "") {
      obj.failReason = message.failReason;
    }
    if (message.releaseFailCount !== 0) {
      obj.releaseFailCount = Math.round(message.releaseFailCount);
    }
    if (message.processing !== false) {
      obj.processing = message.processing;
    }
    if (message.tssMsgId !== "") {
      obj.tssMsgId = message.tssMsgId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.handleId !== 0) {
      obj.handleId = Math.round(message.handleId);
    }
    if (message.loanAddress !== "") {
      obj.loanAddress = message.loanAddress;
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoanTransaction>, I>>(base?: I): LoanTransaction {
    return LoanTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoanTransaction>, I>>(object: I): LoanTransaction {
    const message = createBaseLoanTransaction();
    message.id = object.id ?? 0;
    message.creator = object.creator ?? "";
    message.collateralId = object.collateralId ?? 0;
    message.collateralSymbol = object.collateralSymbol ?? "";
    message.collateralAmount = object.collateralAmount ?? "";
    message.loanDuration = object.loanDuration ?? 0;
    message.interestRate = object.interestRate ?? "";
    message.loanRate = object.loanRate ?? "";
    message.oraclePrice = object.oraclePrice ?? "";
    message.loanAmount = object.loanAmount ?? "";
    message.status = object.status ?? "";
    message.releaseHash = object.releaseHash ?? "";
    message.confirmedBlockHash = object.confirmedBlockHash ?? "";
    message.time = object.time ?? 0;
    message.failReason = object.failReason ?? "";
    message.releaseFailCount = object.releaseFailCount ?? 0;
    message.processing = object.processing ?? false;
    message.tssMsgId = object.tssMsgId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.handleId = object.handleId ?? 0;
    message.loanAddress = object.loanAddress ?? "";
    message.reserved = object.reserved ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
