// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: cfprotocol/loan/pool_summary.proto

/* eslint-disable */
// @ts-nocheck
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cfprotocol.loan";

export interface PoolSummary {
  totalSupply: string;
  totalBorrow: string;
  availableLiquidity: string;
  dailyCfnRewards: string;
  assets: number;
  reserved: string;
}

function createBasePoolSummary(): PoolSummary {
  return { totalSupply: "", totalBorrow: "", availableLiquidity: "", dailyCfnRewards: "", assets: 0, reserved: "" };
}

export const PoolSummary: MessageFns<PoolSummary> = {
  encode(message: PoolSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalSupply !== "") {
      writer.uint32(10).string(message.totalSupply);
    }
    if (message.totalBorrow !== "") {
      writer.uint32(18).string(message.totalBorrow);
    }
    if (message.availableLiquidity !== "") {
      writer.uint32(26).string(message.availableLiquidity);
    }
    if (message.dailyCfnRewards !== "") {
      writer.uint32(34).string(message.dailyCfnRewards);
    }
    if (message.assets !== 0) {
      writer.uint32(40).uint64(message.assets);
    }
    if (message.reserved !== "") {
      writer.uint32(50).string(message.reserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PoolSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePoolSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.totalSupply = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.totalBorrow = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.availableLiquidity = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.dailyCfnRewards = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.assets = longToNumber(reader.uint64());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.reserved = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PoolSummary {
    return {
      totalSupply: isSet(object.totalSupply) ? globalThis.String(object.totalSupply) : "",
      totalBorrow: isSet(object.totalBorrow) ? globalThis.String(object.totalBorrow) : "",
      availableLiquidity: isSet(object.availableLiquidity) ? globalThis.String(object.availableLiquidity) : "",
      dailyCfnRewards: isSet(object.dailyCfnRewards) ? globalThis.String(object.dailyCfnRewards) : "",
      assets: isSet(object.assets) ? globalThis.Number(object.assets) : 0,
      reserved: isSet(object.reserved) ? globalThis.String(object.reserved) : "",
    };
  },

  toJSON(message: PoolSummary): unknown {
    const obj: any = {};
    if (message.totalSupply !== "") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.totalBorrow !== "") {
      obj.totalBorrow = message.totalBorrow;
    }
    if (message.availableLiquidity !== "") {
      obj.availableLiquidity = message.availableLiquidity;
    }
    if (message.dailyCfnRewards !== "") {
      obj.dailyCfnRewards = message.dailyCfnRewards;
    }
    if (message.assets !== 0) {
      obj.assets = Math.round(message.assets);
    }
    if (message.reserved !== "") {
      obj.reserved = message.reserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PoolSummary>, I>>(base?: I): PoolSummary {
    return PoolSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PoolSummary>, I>>(object: I): PoolSummary {
    const message = createBasePoolSummary();
    message.totalSupply = object.totalSupply ?? "";
    message.totalBorrow = object.totalBorrow ?? "";
    message.availableLiquidity = object.availableLiquidity ?? "";
    message.dailyCfnRewards = object.dailyCfnRewards ?? "";
    message.assets = object.assets ?? 0;
    message.reserved = object.reserved ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
